"""Build Ansible Pad inventory/playbook package files and ZIP bytes."""

from __future__ import annotations

import io
import re
import zipfile

from launchpad.ansible_pad_settings import DEFAULT_ANSIBLE_PAD_HOST

_SENSITIVE_MARKERS = (
    "BEGIN RSA PRIVATE KEY",
    "BEGIN OPENSSH PRIVATE KEY",
    "BEGIN EC PRIVATE KEY",
    "BEGIN DSA PRIVATE KEY",
    "BEGIN PRIVATE KEY",
)


def _inventory_hostname(card: dict) -> str:
    name = str(card.get("name") or "").strip()
    safe = re.sub(r"[^\w\-]+", "_", name).strip("_")
    if safe:
        return safe
    card_id = card.get("id")
    if card_id is not None and str(card_id).strip():
        return f"card_{card_id}"
    return "array"


def _yaml_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _build_inventory(cards: list[dict]) -> str:
    lines = [
        "# Ansible inventory generated by LaunchPad Ansible Pad.",
        "# Array SSH targets; run playbooks from the control host.",
        "all:",
        "  hosts:",
    ]
    emitted_names: set[str] = set()
    for card in cards:
        if not isinstance(card, dict):
            continue
        host = str(card.get("host") or "").strip()
        if not host:
            continue
        inv_name = _inventory_hostname(card)
        if inv_name in emitted_names:
            card_id = str(card.get("id") or "").strip()
            suffix = f"_card_{card_id}" if card_id else "_card"
            candidate = f"{inv_name}{suffix}"
            counter = 2
            while candidate in emitted_names:
                candidate = f"{inv_name}{suffix}_{counter}"
                counter += 1
            inv_name = candidate
        emitted_names.add(inv_name)
        lines.append(f"    {inv_name}:")
        lines.append(f"      ansible_host: {_yaml_quote(host)}")
        lines.append("      ansible_connection: ssh")
        username = str(card.get("username") or "").strip()
        if username:
            lines.append(f"      ansible_user: {_yaml_quote(username)}")
        profile = str(card.get("device_profile") or "").strip()
        if profile:
            lines.append(f"      device_profile: {_yaml_quote(profile)}")
    if len(lines) == 4:
        lines.append("    # No storage cards with host addresses were available at export time.")
    return "\n".join(lines) + "\n"


def _build_readme(control_host: str) -> str:
    return f"""# LaunchPad Ansible Pad package

This package was generated by LaunchPad Ansible Pad.

## Dual-path operator model

- **Path A (LaunchPad native):** Contingency Groups and FlashCopy CGs can run
  `svctask` steps directly from LaunchPad over SSH — no Ansible required.
- **Path B (Ansible):** Copy this package to the Ansible control host
  `{control_host}` and run playbooks there. Array connectivity is via the
  inventory in `inventory/hosts.yml` on that host.

## Quick start on {control_host}

```bash
cd /path/to/this/package
ansible-playbook -i inventory/hosts.yml playbooks/start_fc_consistgrp.yml --check
ansible-playbook -i inventory/hosts.yml playbooks/start_fc_consistgrp.yml -e cg_name=MY_CG
ansible-playbook -i inventory/hosts.yml playbooks/snap_copy_stub.yml --check
```

Use `--check` for dry-run. Private keys and array passwords are not included in
this ZIP; configure SSH/auth on `{control_host}` separately.

## Array connection and targeting

The included tasks use `ansible.builtin.raw`, so the array does not need Python.
The generated inventory sets `ansible_connection: ssh`; configure its SSH
authentication on `{control_host}`. Generated playbooks require an explicit
target, for example `-e 'target_hosts=["site_a"]'`, or use
`--limit site_a`. Do not run a mutating playbook without choosing its target.
"""


def _build_start_fc_consistgrp_playbook() -> str:
    return """---
# Start a FlashCopy consistency group (aligned with LaunchPad FlashCopy CG start_group).
# Array SSH is via Ansible inventory on the control host — not from LaunchPad.
- name: Start FlashCopy consistency group
  hosts: "{{ target_hosts | default([]) }}"
  gather_facts: false
  vars:
    cg_name: ""  # required: consistency group name
  tasks:
    - name: Validate cg_name
      ansible.builtin.assert:
        that:
          - cg_name | length > 0
        fail_msg: "Set cg_name (e.g. -e cg_name=MY_CG)"

    - name: Prepare consistency group start
      ansible.builtin.raw: "svctask prestartfcconsistgrp {{ cg_name | quote }}"
      changed_when: true

    - name: Start consistency group
      ansible.builtin.raw: "svctask startfcconsistgrp {{ cg_name | quote }}"
      changed_when: true
"""


def _build_snap_copy_stub_playbook() -> str:
    return """---
# Snap-copy stub — align tasks with LaunchPad Contingency Preview steps before running.
# See Contingency Groups Preview in LaunchPad for the authoritative step list.
- name: Snap copy stub
  hosts: "{{ target_hosts | default([]) }}"
  gather_facts: false
  vars:
    perform_changes: false  # set true to allow mutating tasks (ignored in --check)
    source_volume: ""       # example: source vdisk name
    snap_volume: ""         # example: target snap vdisk name
    fc_map_name: ""         # example: FlashCopy map name
  tasks:
    - name: Example snap copy map (stub)
      ansible.builtin.raw: >-
        svctask mkfcmap -source {{ source_volume | quote }} -target {{ snap_volume | quote }}
        -name {{ fc_map_name | quote }}
      when: perform_changes | bool and not ansible_check_mode
      changed_when: true

    - name: Example start FlashCopy map (stub)
      ansible.builtin.raw: "svctask startfcmap {{ fc_map_name | quote }}"
      when: perform_changes | bool and not ansible_check_mode
      changed_when: true
"""


def build_ansible_pad_files(
    *,
    cards: list[dict],
    contingency_groups: list[dict],
    control_host: str = DEFAULT_ANSIBLE_PAD_HOST,
) -> dict[str, str]:
    """Return path -> text content map for the Ansible Pad export package."""
    del contingency_groups  # reserved for group_vars in later tasks

    files: dict[str, str] = {
        "README.md": _build_readme(control_host),
        "inventory/hosts.yml": _build_inventory(cards),
        "playbooks/start_fc_consistgrp.yml": _build_start_fc_consistgrp_playbook(),
        "playbooks/snap_copy_stub.yml": _build_snap_copy_stub_playbook(),
    }

    combined = "\n".join(files.values())
    for marker in _SENSITIVE_MARKERS:
        if marker in combined:
            raise ValueError(f"Export must not contain key material ({marker})")

    return files


def build_ansible_pad_zip_bytes(
    *,
    cards: list[dict],
    contingency_groups: list[dict],
    control_host: str = DEFAULT_ANSIBLE_PAD_HOST,
) -> bytes:
    """Return ZIP archive bytes for the Ansible Pad export package."""
    files = build_ansible_pad_files(
        cards=cards,
        contingency_groups=contingency_groups,
        control_host=control_host,
    )
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path, content in sorted(files.items()):
            archive.writestr(path, content)
    return buffer.getvalue()
