"""Built-in LUN Builder templates transcribed from site lookup HTML inventories."""

from __future__ import annotations


_SITE_INVENTORIES = [{'id': 'template-perrysburg-oh',
  'location': 'Perrysburg, OH',
  'profile': 'flashsystem_7200',
  'pool': 'G3_PER_Pool',
  'hosts': ['APB1',
            'APB1C',
            'Bib-pdc-vm04',
            'Bib-pdc-vm05',
            'FC_APB1',
            'pen-peresx-vm01',
            'pen-peresx-vm02',
            'pen-peresx-vm03',
            'pen-peresx-vm04',
            'pen-peresx-vm05',
            'ppermhcdb2',
            'ppermhcdg2',
            'pperptla',
            'pperptlb',
            'pperres01',
            'ppervio03a',
            'ppervio03b',
            'ppervio04a',
            'ppervio04b',
            'tpermhcdb1',
            'tpermhcdb2',
            'tpermhcdg2',
            'VM1_Blade3',
            'VM2_Blade4',
            'VM3_Blade6'],
  'volumes': [('as400_30', '120.00 GiB', ['APB1'], '0'),
              ('as400_31', '120.00 GiB', ['APB1'], '1'),
              ('as400_32', '120.00 GiB', ['APB1'], '2'),
              ('as400_33', '120.00 GiB', ['APB1'], '3'),
              ('as400_34', '120.00 GiB', ['APB1'], '4'),
              ('as400_35', '120.00 GiB', ['APB1'], '5'),
              ('as400_36', '120.00 GiB', ['APB1'], '6'),
              ('as400_37', '120.00 GiB', ['APB1'], '7'),
              ('as400_38', '120.00 GiB', ['APB1'], '8'),
              ('as400_39', '120.00 GiB', ['APB1'], '9'),
              ('as400_40', '120.00 GiB', ['APB1'], '10'),
              ('as400_41', '120.00 GiB', ['APB1'], '11'),
              ('as400_42', '120.00 GiB', ['APB1'], '12'),
              ('as400_43', '120.00 GiB', ['APB1'], '13'),
              ('as400_44', '120.00 GiB', ['APB1'], '14'),
              ('as400_45', '120.00 GiB', ['APB1'], '15'),
              ('as400_46', '120.00 GiB', ['APB1'], '16'),
              ('as400_47', '120.00 GiB', ['APB1'], '17'),
              ('as400_48', '120.00 GiB', ['APB1'], '18'),
              ('as400_49', '120.00 GiB', ['APB1'], '19'),
              ('as400_50', '120.00 GiB', ['APB1'], '20'),
              ('as400_51', '120.00 GiB', ['APB1'], '21'),
              ('as400_52', '120.00 GiB', ['APB1'], '22'),
              ('as400_53', '120.00 GiB', ['APB1'], '23'),
              ('as400_54', '120.00 GiB', ['APB1'], '24'),
              ('as400_55', '120.00 GiB', ['APB1'], '25'),
              ('as400_56', '120.00 GiB', ['APB1'], '26'),
              ('as400_57', '120.00 GiB', ['APB1'], '27'),
              ('as400_58', '120.00 GiB', ['APB1'], '28'),
              ('as400_59', '120.00 GiB', ['APB1'], '29'),
              ('as400_60', '120.00 GiB', ['APB1'], '30'),
              ('as400_61', '120.00 GiB', ['APB1'], '31'),
              ('as400_62', '120.00 GiB', ['APB1'], '32'),
              ('as400_63', '120.00 GiB', ['APB1'], '33'),
              ('as400_64', '120.00 GiB', ['APB1'], '34'),
              ('as400_65', '120.00 GiB', ['APB1'], '35'),
              ('as400_66', '120.00 GiB', ['APB1'], '36'),
              ('as400_67', '120.00 GiB', ['APB1'], '37'),
              ('as400_68', '120.00 GiB', ['APB1'], '38'),
              ('as400_69', '120.00 GiB', ['APB1'], '39'),
              ('as400_70', '120.00 GiB', ['APB1'], '40'),
              ('as400_71', '120.00 GiB', ['APB1'], '41'),
              ('as400_72', '120.00 GiB', ['APB1'], '42'),
              ('as400_73', '120.00 GiB', ['APB1'], '43'),
              ('as400_74', '120.00 GiB', ['APB1'], '44'),
              ('as400_75', '120.00 GiB', ['APB1'], '45'),
              ('as400_76', '120.00 GiB', ['APB1'], '46'),
              ('as400_77', '120.00 GiB', ['APB1'], '47'),
              ('APB1C_as400_1', '200.00 GiB', ['APB1C'], '0'),
              ('APB1C_as400_2', '200.00 GiB', ['APB1C'], '1'),
              ('APB1C_as400_3', '200.00 GiB', ['APB1C'], '2'),
              ('APB1C_as400_4', '200.00 GiB', ['APB1C'], '3'),
              ('FC_APB1_as400_1', '120.00 GiB', ['FC_APB1'], '0'),
              ('FC_APB1_as400_2', '120.00 GiB', ['FC_APB1'], '1'),
              ('FC_APB1_as400_3', '120.00 GiB', ['FC_APB1'], '2'),
              ('FC_APB1_as400_4', '120.00 GiB', ['FC_APB1'], '3'),
              ('FC_APB1_as400_5', '120.00 GiB', ['FC_APB1'], '4'),
              ('FC_APB1_as400_6', '120.00 GiB', ['FC_APB1'], '5'),
              ('FC_APB1_as400_7', '120.00 GiB', ['FC_APB1'], '6'),
              ('FC_APB1_as400_8', '120.00 GiB', ['FC_APB1'], '7'),
              ('FC_APB1_as400_9', '120.00 GiB', ['FC_APB1'], '8'),
              ('FC_APB1_as400_10', '120.00 GiB', ['FC_APB1'], '9'),
              ('FC_APB1_as400_11', '120.00 GiB', ['FC_APB1'], '10'),
              ('FC_APB1_as400_12', '120.00 GiB', ['FC_APB1'], '11'),
              ('FC_APB1_as400_13', '120.00 GiB', ['FC_APB1'], '12'),
              ('FC_APB1_as400_14', '120.00 GiB', ['FC_APB1'], '13'),
              ('FC_APB1_as400_15', '120.00 GiB', ['FC_APB1'], '14'),
              ('FC_APB1_as400_16', '120.00 GiB', ['FC_APB1'], '15'),
              ('FC_APB1_as400_17', '120.00 GiB', ['FC_APB1'], '16'),
              ('FC_APB1_as400_18', '120.00 GiB', ['FC_APB1'], '17'),
              ('FC_APB1_as400_19', '120.00 GiB', ['FC_APB1'], '18'),
              ('FC_APB1_as400_20', '120.00 GiB', ['FC_APB1'], '19'),
              ('FC_APB1_as400_21', '120.00 GiB', ['FC_APB1'], '20'),
              ('FC_APB1_as400_22', '120.00 GiB', ['FC_APB1'], '21'),
              ('FC_APB1_as400_23', '120.00 GiB', ['FC_APB1'], '22'),
              ('FC_APB1_as400_24', '120.00 GiB', ['FC_APB1'], '23'),
              ('FC_APB1_as400_25', '120.00 GiB', ['FC_APB1'], '24'),
              ('FC_APB1_as400_26', '120.00 GiB', ['FC_APB1'], '25'),
              ('FC_APB1_as400_27', '120.00 GiB', ['FC_APB1'], '26'),
              ('FC_APB1_as400_28', '120.00 GiB', ['FC_APB1'], '27'),
              ('FC_APB1_as400_29', '120.00 GiB', ['FC_APB1'], '28'),
              ('FC_APB1_as400_30', '120.00 GiB', ['FC_APB1'], '29'),
              ('FC_APB1_as400_31', '120.00 GiB', ['FC_APB1'], '30'),
              ('FC_APB1_as400_32', '120.00 GiB', ['FC_APB1'], '31'),
              ('FC_APB1_as400_33', '120.00 GiB', ['FC_APB1'], '32'),
              ('FC_APB1_as400_34', '120.00 GiB', ['FC_APB1'], '33'),
              ('FC_APB1_as400_35', '120.00 GiB', ['FC_APB1'], '34'),
              ('FC_APB1_as400_36', '120.00 GiB', ['FC_APB1'], '35'),
              ('FC_APB1_as400_37', '120.00 GiB', ['FC_APB1'], '36'),
              ('FC_APB1_as400_38', '120.00 GiB', ['FC_APB1'], '37'),
              ('FC_APB1_as400_39', '120.00 GiB', ['FC_APB1'], '38'),
              ('FC_APB1_as400_40', '120.00 GiB', ['FC_APB1'], '39'),
              ('FC_APB1_as400_41', '120.00 GiB', ['FC_APB1'], '40'),
              ('FC_APB1_as400_42', '120.00 GiB', ['FC_APB1'], '41'),
              ('FC_APB1_as400_43', '120.00 GiB', ['FC_APB1'], '42'),
              ('FC_APB1_as400_44', '120.00 GiB', ['FC_APB1'], '43'),
              ('FC_APB1_as400_45', '120.00 GiB', ['FC_APB1'], '44'),
              ('FC_APB1_as400_46', '120.00 GiB', ['FC_APB1'], '45'),
              ('FC_APB1_as400_47', '120.00 GiB', ['FC_APB1'], '46'),
              ('FC_APB1_as400_48', '120.00 GiB', ['FC_APB1'], '47'),
              ('PDC_4TB_Data_05',
               '4.00 TiB',
               ['pen-peresx-vm01',
                'pen-peresx-vm02',
                'pen-peresx-vm03',
                'pen-peresx-vm04',
                'pen-peresx-vm05'],
               '0'),
              ('PDC_4TB_Data_06',
               '4.00 TiB',
               ['pen-peresx-vm01',
                'pen-peresx-vm02',
                'pen-peresx-vm03',
                'pen-peresx-vm04',
                'pen-peresx-vm05'],
               '1'),
              ('PDC_4TB_Data_07',
               '4.00 TiB',
               ['pen-peresx-vm01',
                'pen-peresx-vm02',
                'pen-peresx-vm03',
                'pen-peresx-vm04',
                'pen-peresx-vm05'],
               '2'),
              ('PDC_4TB_Data_01',
               '5.00 TiB',
               ['pen-peresx-vm01',
                'pen-peresx-vm02',
                'pen-peresx-vm03',
                'pen-peresx-vm04',
                'pen-peresx-vm05'],
               '8'),
              ('PDC_4TB_Data_02',
               '4.00 TiB',
               ['pen-peresx-vm01',
                'pen-peresx-vm02',
                'pen-peresx-vm03',
                'pen-peresx-vm04',
                'pen-peresx-vm05'],
               '9'),
              ('PDC_4TB_Data_03',
               '4.00 TiB',
               ['pen-peresx-vm01',
                'pen-peresx-vm02',
                'pen-peresx-vm03',
                'pen-peresx-vm04',
                'pen-peresx-vm05'],
               '10'),
              ('PDC_4TB_Data_04',
               '4.00 TiB',
               ['pen-peresx-vm01',
                'pen-peresx-vm02',
                'pen-peresx-vm03',
                'pen-peresx-vm04',
                'pen-peresx-vm05'],
               '11'),
              ('tpermhcdb1', '600.00 GiB', ['tpermhcdb1'], '0'),
              ('tpermhcdb1_0', '50.00 GiB', ['tpermhcdb1'], '1'),
              ('tpermhcdb1_1', '50.00 GiB', ['tpermhcdb1'], '2'),
              ('tpermhcdb1_2', '50.00 GiB', ['tpermhcdb1'], '3'),
              ('tpermhcdb2_root_01', '50.00 GiB', ['tpermhcdb2'], '0'),
              ('tpermhcdb2_root_02', '50.00 GiB', ['tpermhcdb2'], '1'),
              ('tpermhcdb2_root_03', '50.00 GiB', ['tpermhcdb2'], '2'),
              ('tpermhcdb2_data_01', '100.00 GiB', ['tpermhcdb2'], '3'),
              ('tpermhcdb2_data_02', '100.00 GiB', ['tpermhcdb2'], '4'),
              ('tpermhcdb2_data_03', '100.00 GiB', ['tpermhcdb2'], '5'),
              ('tpermhcdb2_data_04', '100.00 GiB', ['tpermhcdb2'], '6'),
              ('tpermhcdb2_data_05', '100.00 GiB', ['tpermhcdb2'], '7'),
              ('tpermhcdb2_ASM_Data_01', '100.00 GiB', ['tpermhcdb2'], '8'),
              ('tpermhcdb2_ASM_Data_02', '100.00 GiB', ['tpermhcdb2'], '9'),
              ('tpermhcdb2_ASM_Data_03', '100.00 GiB', ['tpermhcdb2'], '10'),
              ('tpermhcdb2_ASM_Data_04', '100.00 GiB', ['tpermhcdb2'], '11'),
              ('tpermhcdb2_ASM_Test_1', '100.00 GiB', ['tpermhcdb2'], '12'),
              ('tpermhcdb2_ASM_Test_2', '100.00 GiB', ['tpermhcdb2'], '13'),
              ('tpermhcdb2_ASM_Test_3', '100.00 GiB', ['tpermhcdb2'], '14'),
              ('tpermhcdb2_ASM_Test_4', '100.00 GiB', ['tpermhcdb2'], '15'),
              ('tpermhcdg2_root_0', '50.00 GiB', ['tpermhcdg2'], '0'),
              ('tpermhcdg2_root_1', '50.00 GiB', ['tpermhcdg2'], '1'),
              ('tpermhcdg2_root_2', '50.00 GiB', ['tpermhcdg2'], '2'),
              ('tpermhcdg2_data_1', '100.00 GiB', ['tpermhcdg2'], '3'),
              ('tpermhcdg2_data_2', '100.00 GiB', ['tpermhcdg2'], '4'),
              ('tpermhcdg2_data_3', '100.00 GiB', ['tpermhcdg2'], '5'),
              ('tpermhcdg2_data_4', '100.00 GiB', ['tpermhcdg2'], '6'),
              ('tpermhcdg2_data_5', '100.00 GiB', ['tpermhcdg2'], '7'),
              ('tpermhcdg2_data_6', '100.00 GiB', ['tpermhcdg2'], '8'),
              ('tpermhcdg2_data_7', '100.00 GiB', ['tpermhcdg2'], '9'),
              ('tpermhcdg2_data_8', '100.00 GiB', ['tpermhcdg2'], '10'),
              ('tpermhcdg2_data_9', '100.00 GiB', ['tpermhcdg2'], '11'),
              ('ppermhcdb2_0', '50.00 GiB', ['ppermhcdb2'], '0'),
              ('ppermhcdb2_1', '50.00 GiB', ['ppermhcdb2'], '1'),
              ('ppermhcdb2_2', '50.00 GiB', ['ppermhcdb2'], '2'),
              ('ppermhcdb2_data_1', '100.00 GiB', ['ppermhcdb2'], '3'),
              ('ppermhcdb2_data_2', '100.00 GiB', ['ppermhcdb2'], '4'),
              ('ppermhcdb2_data_3', '100.00 GiB', ['ppermhcdb2'], '5'),
              ('ppermhcdb2_data_4', '100.00 GiB', ['ppermhcdb2'], '6'),
              ('ppermhcdb2_data_5', '100.00 GiB', ['ppermhcdb2'], '7'),
              ('ppermhcdb2_data_6', '100.00 GiB', ['ppermhcdb2'], '8'),
              ('ppermhcdb2_data_7', '100.00 GiB', ['ppermhcdb2'], '9'),
              ('ppermhcdb2_data_8', '100.00 GiB', ['ppermhcdb2'], '10'),
              ('ppermhcdb2_data_9', '100.00 GiB', ['ppermhcdb2'], '11'),
              ('ppermhcdg2_root_01_01', '50.00 GiB', ['ppermhcdg2'], '0'),
              ('ppermhcdg2_root_02_01', '50.00 GiB', ['ppermhcdg2'], '1'),
              ('ppermhcdg2_root_03_01', '50.00 GiB', ['ppermhcdg2'], '2'),
              ('ppermhcdg2_data_01_01', '100.00 GiB', ['ppermhcdg2'], '3'),
              ('ppermhcdg2_data_02_01', '100.00 GiB', ['ppermhcdg2'], '4'),
              ('ppermhcdg2_data_03_01', '100.00 GiB', ['ppermhcdg2'], '5'),
              ('ppermhcdg2_data_04_01', '100.00 GiB', ['ppermhcdg2'], '6'),
              ('ppermhcdg2_data_05_01', '100.00 GiB', ['ppermhcdg2'], '7'),
              ('ppermhcdg2_data_06', '100.00 GiB', ['ppermhcdg2'], '8'),
              ('ppermhcdg2_data_07', '100.00 GiB', ['ppermhcdg2'], '9'),
              ('ppermhcdg2_data_08', '100.00 GiB', ['ppermhcdg2'], '10'),
              ('ppermhcdg2_data_09', '100.00 GiB', ['ppermhcdg2'], '11'),
              ('pperres01_00', '100.00 GiB', ['pperres01'], '0'),
              ('pperres01_01', '100.00 GiB', ['pperres01'], '1'),
              ('pperres01_02', '100.00 GiB', ['pperres01'], '2'),
              ('pperres01_03', '100.00 GiB', ['pperres01'], '3'),
              ('pperres01_04', '100.00 GiB', ['pperres01'], '4'),
              ('ppervio03a_root_1', '100.00 GiB', ['ppervio03a'], '0'),
              ('ppervio03a_root_2', '100.00 GiB', ['ppervio03a'], '1'),
              ('ppervio03b_root_1', '100.00 GiB', ['ppervio03b'], '0'),
              ('ppervio03b_root_2', '100.00 GiB', ['ppervio03b'], '1'),
              ('ppervio04a_root_1', '100.00 GiB', ['ppervio04a'], '0'),
              ('ppervio04a_root_2', '100.00 GiB', ['ppervio04a'], '1'),
              ('ppervio04b_root_1', '100.00 GiB', ['ppervio04b'], '0'),
              ('ppervio04b_root_2', '100.00 GiB', ['ppervio04b'], '1')]},
 {'id': 'template-moreno-valley-ca',
  'location': 'Moreno Valley, CA',
  'profile': 'flashsystem_5200',
  'pool': 'MOR_G3_Pool',
  'hosts': ['AMO1_New',
            'AMO1C',
            'FC_AMO1',
            'pen-moresx-vm01',
            'pen-moresx-vm02',
            'pen-moresx-vm03',
            'pmormhcdb1',
            'pmormhcdb2',
            'pmormhcdg1',
            'pmormhcdg2',
            'pmorres01',
            'pmorvio01a',
            'pmorvio01b',
            'pmorvio1',
            'pmorvio02a',
            'pmorvio02b',
            'pmorvio03a',
            'pmorvio03b',
            'pmorvio04a',
            'pmorvio04b',
            'pmorvio4',
            'pmorvio5',
            'pmorvm1',
            'pmorvm2',
            'pmorvm3',
            'tmormhcdb1'],
  'volumes': [('MOR_DataStore_1', '4.00 TiB', ['pen-moresx-vm02', 'pen-moresx-vm03'], '0'),
              ('MOR_DataStore_2', '4.00 TiB', ['pen-moresx-vm02', 'pen-moresx-vm03'], '1'),
              ('MOR_DataStore_3', '4.00 TiB', ['pen-moresx-vm02', 'pen-moresx-vm03'], '2'),
              ('MOR_DataStore_4', '4.00 TiB', ['pen-moresx-vm02', 'pen-moresx-vm03'], '3'),
              ('MOR_DataStore_5', '4.00 TiB', ['pen-moresx-vm02', 'pen-moresx-vm03'], '4'),
              ('MOR_DataStore_6', '4.00 TiB', ['pen-moresx-vm02', 'pen-moresx-vm03'], '5'),
              ('pmormhcdb2_root_1', '50.00 GiB', ['pmormhcdb2'], '0'),
              ('pmormhcdb2_root_2', '50.00 GiB', ['pmormhcdb2'], '1'),
              ('pmormhcdb2_root_3', '50.00 GiB', ['pmormhcdb2'], '2'),
              ('pmormhcdb2_Data_1', '100.00 GiB', ['pmormhcdb2'], '3'),
              ('pmormhcdb2_Data_2', '100.00 GiB', ['pmormhcdb2'], '4'),
              ('pmormhcdb2_Data_3', '100.00 GiB', ['pmormhcdb2'], '5'),
              ('pmormhcdb2_Data_4', '100.00 GiB', ['pmormhcdb2'], '6'),
              ('pmormhcdb2_Data_5', '100.00 GiB', ['pmormhcdb2'], '7'),
              ('pmormhcdb2_Data_6', '100.00 GiB', ['pmormhcdb2'], '8'),
              ('pmormhcdb2_Data_7', '100.00 GiB', ['pmormhcdb2'], '9'),
              ('pmormhcdb2_Data_8', '100.00 GiB', ['pmormhcdb2'], '10'),
              ('pmormhcdb2_Data_9', '100.00 GiB', ['pmormhcdb2'], '11'),
              ('pmorvio01a_root_1', '100.00 GiB', ['pmorvio01a'], '0'),
              ('pmorvio01a_root_2', '100.00 GiB', ['pmorvio01a'], '1'),
              ('pmorvio01b_root_1', '100.00 GiB', ['pmorvio01b'], '0'),
              ('pmorvio01b_root_2', '100.00 GiB', ['pmorvio01b'], '1'),
              ('pmorvio02a_root_1', '100.00 GiB', ['pmorvio02a'], '0'),
              ('pmorvio02a_root_2', '100.00 GiB', ['pmorvio02a'], '1'),
              ('pmorvio02b_root_1', '100.00 GiB', ['pmorvio02b'], '0'),
              ('pmorvio02b_root_2', '100.00 GiB', ['pmorvio02b'], '1'),
              ('pmorvio03a_3_4_shared_1', '100.00 GiB', ['pmorvio03a'], '0'),
              ('pmorvio03a_3_4_shared_2', '100.00 GiB', ['pmorvio03a'], '1'),
              ('pmorvio03b_3_4_shared_1', '100.00 GiB', ['pmorvio03b'], '0'),
              ('pmorvio03b_3_4_shared_2', '100.00 GiB', ['pmorvio03b'], '1'),
              ('pmorvio04a_3_4_shared_1', '100.00 GiB', ['pmorvio04a'], '0'),
              ('pmorvio04a_3_4_shared_2', '100.00 GiB', ['pmorvio04a'], '1'),
              ('pmorvio04b_3_4_shared_1', '100.00 GiB', ['pmorvio04b'], '0'),
              ('pmorvio04b_3_4_shared_2', '100.00 GiB', ['pmorvio04b'], '1'),
              ('pmorres01_00', '100.00 GiB', ['pmorres01'], '0'),
              ('pmorres01_01', '100.00 GiB', ['pmorres01'], '1'),
              ('pmorres01_02', '100.00 GiB', ['pmorres01'], '2'),
              ('pmorres01_03', '100.00 GiB', ['pmorres01'], '3'),
              ('pmorres01_04', '100.00 GiB', ['pmorres01'], '4'),
              ('pmormhcdg2_root_1', '50.00 GiB', ['pmormhcdg2'], '0'),
              ('pmormhcdg2_root_2', '50.00 GiB', ['pmormhcdg2'], '1'),
              ('pmormhcdg2_root_3', '50.00 GiB', ['pmormhcdg2'], '2'),
              ('pmormhcdg2_Data_1', '100.00 GiB', ['pmormhcdg2'], '3'),
              ('pmormhcdg2_Data_2', '100.00 GiB', ['pmormhcdg2'], '4'),
              ('pmormhcdg2_Data_3', '100.00 GiB', ['pmormhcdg2'], '5'),
              ('pmormhcdg2_Data_4', '100.00 GiB', ['pmormhcdg2'], '6'),
              ('pmormhcdg2_Data_5', '100.00 GiB', ['pmormhcdg2'], '7'),
              ('pmormhcdg2_Data_6', '100.00 GiB', ['pmormhcdg2'], '8'),
              ('pmormhcdg2_Data_7', '100.00 GiB', ['pmormhcdg2'], '9'),
              ('pmormhcdg2_Data_8', '100.00 GiB', ['pmormhcdg2'], '10'),
              ('pmormhcdg2_Data_9', '100.00 GiB', ['pmormhcdg2'], '11')]},
 {'id': 'template-nazareth-pa',
  'location': 'Nazareth, PA',
  'profile': 'flashsystem_5200',
  'pool': 'V5kNAZ_Pool1',
  'hosts': ['pen-nazesx-vm05', 'pen-nazesx-vm06'],
  'volumes': [('Nazesx03_04_Datastore_1', '2.24 TiB', ['pen-nazesx-vm05', 'pen-nazesx-vm06'], '0'),
              ('Nazesx03_04_Datastore_2', '2.00 TiB', ['pen-nazesx-vm05', 'pen-nazesx-vm06'], '1'),
              ('Nnazesx03_04_Datastore_3', '4.00 TiB', ['pen-nazesx-vm05', 'pen-nazesx-vm06'], '2'),
              ('Nazesx03_04_Datastore_4',
               '10.00 TiB',
               ['pen-nazesx-vm05', 'pen-nazesx-vm06'],
               '3')]},
 {'id': 'template-valparaiso-in',
  'location': 'Valparaiso, IN',
  'profile': 'flashsystem_7300',
  'pool': 'VAL_POOL',
  'hosts': ['pen-valesx-vm01',
            'pen-valesx-vm02',
            'pvalap01',
            'pvaldb01',
            'pvalres01',
            'pvalvio01a',
            'pvalvio01b',
            'pvalvio02a',
            'pvalvio02b',
            'pvalws01'],
  'volumes': [('pen_valesx_DataStore_1', '4.00 TiB', ['pen-valesx-vm01', 'pen-valesx-vm02'], ''),
              ('pen_valesx_DataStore_2', '4.00 TiB', ['pen-valesx-vm01', 'pen-valesx-vm02'], ''),
              ('pvalap01-rootvg', '50.00 GiB', ['pvalap01'], '2'),
              ('pvalap01-sysvg', '50.00 GiB', ['pvalap01'], '3'),
              ('pvalap01-altvg', '50.00 GiB', ['pvalap01'], '0'),
              ('pvalap01-appvg', '100.00 GiB', ['pvalap01'], '1'),
              ('pvaldb01-rootvg', '50.00 GiB', ['pvaldb01'], '1'),
              ('pvaldb01-sysvg', '50.00 GiB', ['pvaldb01'], '2'),
              ('pvaldb01-altvg', '50.00 GiB', ['pvaldb01'], '0'),
              ('pvaldb01_01', '200.00 GiB', ['pvaldb01'], '3'),
              ('pvaldb01_02', '200.00 GiB', ['pvaldb01'], '4'),
              ('pvaldb01_03', '200.00 GiB', ['pvaldb01'], '5'),
              ('pvaldb01_4', '20.00 GiB', ['pvaldb01'], '6'),
              ('pvalres01_00', '100.00 GiB', ['pvalres01'], '0'),
              ('pvalres01_01', '100.00 GiB', ['pvalres01'], '1'),
              ('pvalres01_02', '100.00 GiB', ['pvalres01'], '2'),
              ('pvalres01_03', '100.00 GiB', ['pvalres01'], '3'),
              ('pvalres01_04', '100.00 GiB', ['pvalres01'], '4'),
              ('pvalvio01a_root_1', '100.00 GiB', ['pvalvio01a'], '0'),
              ('pvalvio01a_root_2', '100.00 GiB', ['pvalvio01a'], '1'),
              ('pvalvio01b_root_1', '100.00 GiB', ['pvalvio01b'], '0'),
              ('pvalvio01b_root_2', '100.00 GiB', ['pvalvio01b'], '1'),
              ('pvalvio02a_root_1', '100.00 GiB', ['pvalvio02a'], '0'),
              ('pvalvio02a_root_2', '100.00 GiB', ['pvalvio02a'], '1'),
              ('pvalvio02b_root_1', '100.00 GiB', ['pvalvio02b'], '0'),
              ('pvalvio02b_root_2', '100.00 GiB', ['pvalvio02b'], '1'),
              ('pvalws01-rootvg', '50.00 GiB', ['pvalws01'], '1'),
              ('pvalws01-sysvg', '50.00 GiB', ['pvalws01'], '2'),
              ('pvalws01-altvg', '50.00 GiB', ['pvalws01'], '0'),
              ('pvalws01_1', '50.00 GiB', ['pvalws01'], '3'),
              ('pvalws01_2', '100.00 GiB', ['pvalws01'], '4')]},
 {'id': 'template-waxahachie-tx',
  'location': 'Waxahachie, TX',
  'profile': 'flashsystem_5200',
  'pool': 'Wax_Pool1',
  'hosts': ['AWX1',
            'AWX1C',
            'FC_AWX1',
            'pen-waxesx-vm01',
            'pen-waxesx-vm02',
            'pen-waxesx-vm03',
            'pwaxmhcdb2',
            'pwaxmhcdg2',
            'pwaxres01',
            'pwaxvio01a',
            'pwaxvio01b',
            'pwaxvio02a',
            'pwaxvio02b',
            'twaxmhcdb1'],
  'volumes': [('AS400_Wax_1', '', ['AWX1'], ''),
              ('AS400_Wax_2', '', ['AWX1'], ''),
              ('AS400_Wax_3', '', ['AWX1'], ''),
              ('AS400_Wax_4', '', ['AWX1'], ''),
              ('AS400_Wax_5', '', ['AWX1'], ''),
              ('AS400_Wax_6', '', ['AWX1'], ''),
              ('AS400_Wax_7', '', ['AWX1'], ''),
              ('AS400_Wax_8', '', ['AWX1'], ''),
              ('AS400_Wax_9', '', ['AWX1'], ''),
              ('AS400_Wax_10', '', ['AWX1'], ''),
              ('AS400_Wax_11', '', ['AWX1'], ''),
              ('AS400_Wax_12', '', ['AWX1'], ''),
              ('AS400_Wax_13', '', ['AWX1'], ''),
              ('AS400_Wax_14', '', ['AWX1'], ''),
              ('AS400_Wax_15', '', ['AWX1'], ''),
              ('AS400_Wax_16', '', ['AWX1'], ''),
              ('AS400_Wax_17', '', ['AWX1'], ''),
              ('AS400_Wax_18', '', ['AWX1'], ''),
              ('AS400_Wax_19', '', ['AWX1'], ''),
              ('AS400_Wax_20', '', ['AWX1'], ''),
              ('AS400_Wax_21', '', ['AWX1'], ''),
              ('AS400_Wax_22', '', ['AWX1'], ''),
              ('AS400_Wax_23', '', ['AWX1'], ''),
              ('AS400_Wax_24', '', ['AWX1'], ''),
              ('AWX1C_AS400_wax_1', '', ['AWX1C'], ''),
              ('AWX1C_AS400_wax_2', '', ['AWX1C'], ''),
              ('AWX1C_AS400_wax_3', '', ['AWX1C'], ''),
              ('AWX1C_AS400_wax_4', '', ['AWX1C'], ''),
              ('FC_AWX1_wax_1', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_2', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_3', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_4', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_5', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_6', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_7', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_8', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_9', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_10', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_11', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_12', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_13', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_14', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_15', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_16', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_17', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_18', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_19', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_20', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_21', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_22', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_23', '', ['FC_AWX1'], ''),
              ('FC_AWX1_wax_24', '', ['FC_AWX1'], ''),
              ('WAX_ESXI_DS_01', '', ['pen-waxesx-vm01', 'pen-waxesx-vm02', 'pen-waxesx-vm03'], ''),
              ('WAX_ESXI_DS_02', '', ['pen-waxesx-vm01', 'pen-waxesx-vm02', 'pen-waxesx-vm03'], ''),
              ('WAX_ESXI_DS_03', '', ['pen-waxesx-vm01', 'pen-waxesx-vm02', 'pen-waxesx-vm03'], ''),
              ('WAX_ESXI_DS_04', '', ['pen-waxesx-vm01', 'pen-waxesx-vm02', 'pen-waxesx-vm03'], ''),
              ('pwaxmhcdb2_root_1', '', ['pwaxmhcdb2'], ''),
              ('pwaxmhcdb2_root_2', '', ['pwaxmhcdb2'], ''),
              ('pwaxmhcdb2_root_3', '', ['pwaxmhcdb2'], ''),
              ('pwaxmhcdb2_data_1', '', ['pwaxmhcdb2'], ''),
              ('pwaxmhcdb2_data_2', '', ['pwaxmhcdb2'], ''),
              ('pwaxmhcdb2_data_3', '', ['pwaxmhcdb2'], ''),
              ('pwaxmhcdb2_data_4', '', ['pwaxmhcdb2'], ''),
              ('pwaxmhcdb2_data_5', '', ['pwaxmhcdb2'], ''),
              ('pwaxmhcdb2_data_6', '', ['pwaxmhcdb2'], ''),
              ('pwaxmhcdb2_data_7', '', ['pwaxmhcdb2'], ''),
              ('pwaxmhcdb2_data_8', '', ['pwaxmhcdb2'], ''),
              ('pwaxmhcdb2_data_9', '', ['pwaxmhcdb2'], ''),
              ('pwaxmhcdg2_root_1', '', ['pwaxmhcdg2'], ''),
              ('pwaxmhcdg2_root_2', '', ['pwaxmhcdg2'], ''),
              ('pwaxmhcdg2_root_3', '', ['pwaxmhcdg2'], ''),
              ('pwaxmhcdg2_data_1', '', ['pwaxmhcdg2'], ''),
              ('pwaxmhcdg2_data_2', '', ['pwaxmhcdg2'], ''),
              ('pwaxmhcdg2_data_3', '', ['pwaxmhcdg2'], ''),
              ('pwaxmhcdg2_data_4', '', ['pwaxmhcdg2'], ''),
              ('pwaxmhcdg2_data_5', '', ['pwaxmhcdg2'], ''),
              ('pwaxmhcdg2_data_6', '', ['pwaxmhcdg2'], ''),
              ('pwaxmhcdg2_data_7', '', ['pwaxmhcdg2'], ''),
              ('pwaxmhcdg2_data_8', '', ['pwaxmhcdg2'], ''),
              ('pwaxmhcdg2_data_9', '', ['pwaxmhcdg2'], ''),
              ('pwaxres01_00', '', ['pwaxres01'], ''),
              ('pwaxres01_01', '', ['pwaxres01'], ''),
              ('pwaxres01_02', '', ['pwaxres01'], ''),
              ('pwaxres01_03', '', ['pwaxres01'], ''),
              ('pwaxres01_04', '', ['pwaxres01'], ''),
              ('pwaxvio01a_1', '', ['pwaxvio01a'], ''),
              ('pwaxvio01a_2', '', ['pwaxvio01a'], ''),
              ('pwaxvio01b_1', '', ['pwaxvio01b'], ''),
              ('pwaxvio01b_2', '', ['pwaxvio01b'], ''),
              ('pwaxvio01b_3', '', ['pwaxvio01b'], ''),
              ('pwaxvio01b_4', '', ['pwaxvio01b'], ''),
              ('pwaxvio01b_5', '', ['pwaxvio01b'], ''),
              ('pwaxvio02a_1', '', ['pwaxvio02a'], ''),
              ('pwaxvio02a_2', '', ['pwaxvio02a'], ''),
              ('pwaxvio02b_1', '', ['pwaxvio02b'], ''),
              ('pwaxvio02b_2', '', ['pwaxvio02b'], ''),
              ('ntwaxmhcdb1_root_1', '', ['twaxmhcdb1'], ''),
              ('ntwaxmhcdb1_root_2', '', ['twaxmhcdb1'], ''),
              ('ntwaxmhcdb1_root_3', '', ['twaxmhcdb1'], ''),
              ('ntwaxmhcdb1_data_1', '', ['twaxmhcdb1'], '')]},
 {'id': 'template-woodland-hills-ca',
  'location': 'Woodland Hills, CA',
  'profile': 'flashsystem_5200',
  'pool': 'WOO_Pool1',
  'hosts': ['AWD1_New_as400',
            'PEN-WODESX-VM01',
            'PEN-WODESX-VM02',
            'PEN-WODESX-VM03',
            'PEN-WODESX-VM04',
            'pwoovio01a',
            'pwoovio01b',
            'pwoovio02a',
            'pwoovio02b'],
  'volumes': [('WOO_ESX_DataStore_1',
               '',
               ['PEN-WODESX-VM01', 'PEN-WODESX-VM02', 'PEN-WODESX-VM03', 'PEN-WODESX-VM04'],
               '0'),
              ('WOO_ESX_DataStore_2',
               '',
               ['PEN-WODESX-VM01', 'PEN-WODESX-VM02', 'PEN-WODESX-VM03', 'PEN-WODESX-VM04'],
               '1'),
              ('WOO_ESX_DataStore_3',
               '',
               ['PEN-WODESX-VM01', 'PEN-WODESX-VM02', 'PEN-WODESX-VM03', 'PEN-WODESX-VM04'],
               '2'),
              ('WOO_ESX_DataStore_4',
               '',
               ['PEN-WODESX-VM01', 'PEN-WODESX-VM02', 'PEN-WODESX-VM03', 'PEN-WODESX-VM04'],
               '3'),
              ('pwoovio01a_root_1', '', ['pwoovio01a'], '0'),
              ('pwoovio01a_root_2', '', ['pwoovio01a'], '1'),
              ('pwoovio01b_root_1', '', ['pwoovio01b'], '0'),
              ('pwoovio01b_root_2', '', ['pwoovio01b'], '1'),
              ('pwoovio02a_root_1', '', ['pwoovio02a'], '0'),
              ('pwoovio02a_root_2', '', ['pwoovio02a'], '1'),
              ('AWD1_AS400_1', '', ['AWD1_New_as400'], '0'),
              ('AWD1_AS400_2', '', ['AWD1_New_as400'], '1'),
              ('AWD1_AS400_3', '', ['AWD1_New_as400'], '2'),
              ('AWD1_AS400_4', '', ['AWD1_New_as400'], '3'),
              ('AWD1_AS400_5', '', ['AWD1_New_as400'], '4'),
              ('AWD1_AS400_6', '', ['AWD1_New_as400'], '5')]},
 {'id': 'template-orlando-fl',
  'location': 'Orlando, FL',
  'profile': 'ibm_storwize_v7000',
  'pool': 'G1_CPO_Pool',
  'hosts': ['porlpls1', 'porlpls2'],
  'volumes': [('oraclevg_0', '200.00 GiB', ['porlpls1', 'porlpls2'], ''),
              ('oraclevg_1', '200.00 GiB', ['porlpls1', 'porlpls2'], ''),
              ('oraclevg_2', '200.00 GiB', ['porlpls1', 'porlpls2'], ''),
              ('oraclevg_3', '200.00 GiB', ['porlpls1', 'porlpls2'], ''),
              ('oraclevg_4', '200.00 GiB', ['porlpls1', 'porlpls2'], ''),
              ('oraclevg_5', '200.00 GiB', ['porlpls1', 'porlpls2'], ''),
              ('oraclevg_6', '200.00 GiB', ['porlpls1', 'porlpls2'], ''),
              ('oraclevg_7', '200.00 GiB', ['porlpls1', 'porlpls2'], ''),
              ('pls_cluster_repo', '10.00 GiB', ['porlpls1', 'porlpls2'], ''),
              ('porlpls1_0', '136.73 GiB', ['porlpls1', 'porlpls2'], ''),
              ('porlpls1_1', '136.73 GiB', ['porlpls1', 'porlpls2'], ''),
              ('porlpls1_2', '136.73 GiB', ['porlpls1', 'porlpls2'], ''),
              ('porlpls2_0', '136.73 GiB', ['porlpls1', 'porlpls2'], ''),
              ('porlpls2_1', '136.73 GiB', ['porlpls1', 'porlpls2'], ''),
              ('porlpls2_2', '136.73 GiB', ['porlpls1', 'porlpls2'], '')]},
 {'id': 'template-carolina-pr',
  'location': 'Carolina, PR',
  'profile': 'flashsystem_7300',
  'pool': 'PR_pool1',
  'hosts': ['APR1',
            'pen_pueesx_vm01',
            'pen_pueesx_vm02',
            'ppuevio01a',
            'ppuevio01b',
            'ppuevio02a',
            'ppuevio02b'],
  'volumes': [('PUESX_VM_DataStore_1', '4.00 TiB', ['pen_pueesx_vm01', 'pen_pueesx_vm02'], ''),
              ('PUESX_VM_DataStore_2', '4.00 TiB', ['pen_pueesx_vm01', 'pen_pueesx_vm02'], ''),
              ('as400_1', '116.00 GiB', ['APR1'], ''),
              ('as400_2', '116.00 GiB', ['APR1'], ''),
              ('as400_3', '116.00 GiB', ['APR1'], ''),
              ('as400_4', '116.00 GiB', ['APR1'], ''),
              ('as400_5', '116.00 GiB', ['APR1'], ''),
              ('as400_6', '116.00 GiB', ['APR1'], ''),
              ('as400_7', '116.00 GiB', ['APR1'], ''),
              ('as400_8', '116.00 GiB', ['APR1'], ''),
              ('as400_9', '116.00 GiB', ['APR1'], ''),
              ('as400_10', '116.00 GiB', ['APR1'], ''),
              ('as400_11', '116.00 GiB', ['APR1'], ''),
              ('as400_12', '116.00 GiB', ['APR1'], ''),
              ('as400_13', '116.00 GiB', ['APR1'], ''),
              ('as400_14', '116.00 GiB', ['APR1'], ''),
              ('as400_15', '116.00 GiB', ['APR1'], ''),
              ('as400_16', '116.00 GiB', ['APR1'], ''),
              ('ppuevio01a_root_1', '100.00 GiB', ['ppuevio01a'], ''),
              ('ppuevio01a_root_2', '100.00 GiB', ['ppuevio01a'], ''),
              ('ppuevio01b_root_1', '100.00 GiB', ['ppuevio01b'], ''),
              ('ppuevio01b_root_2', '100.00 GiB', ['ppuevio01b'], ''),
              ('ppuevio02a_root_1', '100.00 GiB', ['ppuevio02a'], ''),
              ('ppuevio02a_root_2', '100.00 GiB', ['ppuevio02a'], ''),
              ('ppuevio02b_root_1', '100.00 GiB', ['ppuevio02b'], ''),
              ('ppuevio02b_root_2', '100.00 GiB', ['ppuevio02b'], '')]},
 {'id': 'template-anderson-sc',
  'location': 'Anderson, SC',
  'profile': 'flashsystem_7200',
  'pool': 'G3_AND_Pool',
  'hosts': ['AAN1',
            'AAN1C',
            'BIB_ADC_VM01',
            'BIB_ADC_VM02',
            'dandmfs1',
            'FC_AAN1',
            'pandap01',
            'pandap02',
            'pandbt1',
            'pandbt2',
            'pandbt3',
            'pandbt4',
            'pandbtdg1',
            'panddb01',
            'panddb02',
            'pandmfs1',
            'pandmfs10',
            'pandmfs2',
            'pandmfs3',
            'pandmfs4',
            'pandmfsdg1',
            'pandnim01',
            'pandsps1',
            'pandsps2',
            'pandsps3',
            'pandsps4',
            'pandspsa1',
            'pandspsa2',
            'pandspsdg1',
            'pandvio01a',
            'pandvio01b',
            'pandvio02a',
            'pandvio02b',
            'pandvio03a',
            'pandvio03b',
            'pandvio04a',
            'pandvio04b',
            'pandvio05a',
            'pandvio05b',
            'pandvio06a',
            'pandvio06b',
            'pandvio07a',
            'pandvio07b',
            'pandvio08a',
            'pandvio08b',
            'pandvio09a',
            'pandvio09b',
            'pandvio10a',
            'pandvio10b',
            'pen_andesx_vm03',
            'pen_andesx_vm04',
            'pla-wanoemcr01',
            'pla-wanoemcr02',
            'tandbt1',
            'tandbt20',
            'tandmfs1',
            'tandmfs2',
            'tandmfs20',
            'tandsps1',
            'tandsps2',
            'tandsps20',
            'tandsps21',
            'tconbt20',
            'tconmfs20',
            'tconsps20',
            'tconsps21',
            'TLA_WANMFS01',
            'TLA_WANMFS02'],
  'volumes': [('aan1_0', '', ['AAN1'], ''),
              ('aan1_1', '', ['AAN1'], ''),
              ('aan1_2', '', ['AAN1'], ''),
              ('aan1_3', '', ['AAN1'], ''),
              ('aan1_4', '', ['AAN1'], ''),
              ('aan1_5', '', ['AAN1'], ''),
              ('aan1_6', '', ['AAN1'], ''),
              ('aan1_7', '', ['AAN1'], ''),
              ('aan1_8', '', ['AAN1'], ''),
              ('aan1_9', '', ['AAN1'], ''),
              ('aan1_10', '', ['AAN1'], ''),
              ('aan1_11', '', ['AAN1'], ''),
              ('aan1_12', '', ['AAN1'], ''),
              ('aan1_13', '', ['AAN1'], ''),
              ('aan1_14', '', ['AAN1'], ''),
              ('aan1_15', '', ['AAN1'], ''),
              ('aan1_16', '', ['AAN1'], ''),
              ('aan1_17', '', ['AAN1'], ''),
              ('aan1_18', '', ['AAN1'], ''),
              ('aan1_19', '', ['AAN1'], ''),
              ('aan1_20', '', ['AAN1'], ''),
              ('aan1_21', '', ['AAN1'], ''),
              ('aan1_22', '', ['AAN1'], ''),
              ('aan1_23', '', ['AAN1'], ''),
              ('aan1_24', '', ['AAN1'], ''),
              ('aan1_25', '', ['AAN1'], ''),
              ('aan1_26', '', ['AAN1'], ''),
              ('aan1_27', '', ['AAN1'], ''),
              ('AAN1C_0', '', ['AAN1C'], ''),
              ('AAN1C_1', '', ['AAN1C'], ''),
              ('AAN1C_2', '', ['AAN1C'], ''),
              ('AAN1C_3', '', ['AAN1C'], ''),
              ('Test_VMware_Lun', '', ['BIB_ADC_VM01'], ''),
              ('dandmfs1_0', '', ['dandmfs1'], ''),
              ('dandmfs1_1', '', ['dandmfs1'], ''),
              ('dandmfs1_2', '', ['dandmfs1'], ''),
              ('dandmfs1_3', '', ['dandmfs1'], ''),
              ('dandmfs1_4', '', ['dandmfs1'], ''),
              ('dandmfs1_5', '', ['dandmfs1'], ''),
              ('dandmfs1_6', '', ['dandmfs1'], ''),
              ('dandmfs1_7', '', ['dandmfs1'], ''),
              ('dandmfs1_8', '', ['dandmfs1'], ''),
              ('dandmfs1_9', '', ['dandmfs1'], ''),
              ('dandmfs1_10', '', ['dandmfs1'], ''),
              ('dandmfs1_11', '', ['dandmfs1'], ''),
              ('dandmfs1_12', '', ['dandmfs1'], ''),
              ('dandmfs1_13', '', ['dandmfs1'], ''),
              ('FC_AAN1_0', '', ['FC_AAN1'], ''),
              ('FC_AAN1_1', '', ['FC_AAN1'], ''),
              ('FC_AAN1_2', '', ['FC_AAN1'], ''),
              ('FC_AAN1_3', '', ['FC_AAN1'], ''),
              ('FC_AAN1_4', '', ['FC_AAN1'], ''),
              ('FC_AAN1_5', '', ['FC_AAN1'], ''),
              ('FC_AAN1_6', '', ['FC_AAN1'], ''),
              ('FC_AAN1_7', '', ['FC_AAN1'], ''),
              ('FC_AAN1_8', '', ['FC_AAN1'], ''),
              ('FC_AAN1_9', '', ['FC_AAN1'], ''),
              ('FC_AAN1_10', '', ['FC_AAN1'], ''),
              ('FC_AAN1_11', '', ['FC_AAN1'], ''),
              ('FC_AAN1_12', '', ['FC_AAN1'], ''),
              ('FC_AAN1_13', '', ['FC_AAN1'], ''),
              ('FC_AAN1_14', '', ['FC_AAN1'], ''),
              ('FC_AAN1_15', '', ['FC_AAN1'], ''),
              ('FC_AAN1_16', '', ['FC_AAN1'], ''),
              ('FC_AAN1_17', '', ['FC_AAN1'], ''),
              ('FC_AAN1_18', '', ['FC_AAN1'], ''),
              ('FC_AAN1_19', '', ['FC_AAN1'], ''),
              ('FC_AAN1_20', '', ['FC_AAN1'], ''),
              ('FC_AAN1_21', '', ['FC_AAN1'], ''),
              ('FC_AAN1_22', '', ['FC_AAN1'], ''),
              ('FC_AAN1_23', '', ['FC_AAN1'], ''),
              ('FC_AAN1_24', '', ['FC_AAN1'], ''),
              ('FC_AAN1_25', '', ['FC_AAN1'], ''),
              ('FC_AAN1_26', '', ['FC_AAN1'], ''),
              ('FC_AAN1_27', '', ['FC_AAN1'], ''),
              ('pandap01_0', '', ['pandap01'], ''),
              ('pandap01_1', '', ['pandap01'], ''),
              ('pandap01_2', '', ['pandap01'], ''),
              ('pandap01_3', '', ['pandap01'], ''),
              ('pandap01_4', '', ['pandap01'], ''),
              ('pandap02_1', '', ['pandap02'], ''),
              ('pandap02_2', '', ['pandap02'], ''),
              ('pandap02_0', '', ['pandap02'], ''),
              ('pandap02_03', '', ['pandap02'], ''),
              ('pandap02_04', '', ['pandap02'], ''),
              ('pandbt1_0', '', ['pandbt1'], ''),
              ('pandbt1_1', '', ['pandbt1'], ''),
              ('pandbt1_2', '', ['pandbt1'], ''),
              ('pandbt_1_2_HA', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_1', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_2', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_3', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_4', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_5', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_6', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_7', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_8', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_9', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_10', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_11', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_12', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_13', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_14', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_15', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_16', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_17', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_18', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_19', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_20', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_21', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_22', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_23', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_24', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_25', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_26', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_27', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_28', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_29', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_30', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_31', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_32', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_33', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_34', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_35', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt_1_2_shared_36', '', ['pandbt1', 'pandbt2'], ''),
              ('Pandbt_1_2_Shared_ORAEX_1', '', ['pandbt1', 'pandbt2'], ''),
              ('Pandbt_1_2_Shared_ORAEX_2', '', ['pandbt1', 'pandbt2'], ''),
              ('Pandbt_1_2_Shared_ORAEX_3', '', ['pandbt1', 'pandbt2'], ''),
              ('Pandbt_1_2_Shared_ORAEX_4', '', ['pandbt1', 'pandbt2'], ''),
              ('Pandbt_1_2_Shared_ORAEX_5', '', ['pandbt1', 'pandbt2'], ''),
              ('pandbt2_0', '', ['pandbt2'], ''),
              ('pandbt2_1', '', ['pandbt2'], ''),
              ('pandbt2_2', '', ['pandbt2'], ''),
              ('tandbt20_clone0', '', ['pandbt3', 'pandbt4'], ''),
              ('tandbt20_clone1', '', ['pandbt3', 'pandbt4'], ''),
              ('tandbt20_clone2', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_1', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_2', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_3', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_4', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_5', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_6', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_7', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_8', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_9', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_10', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_11', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_12', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_13', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_14', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_15', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_16', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_17', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_18', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_19', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_20', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_DATA_SHARED_21', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_ARCHVG_SHARED_1', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_ARCHVG_SHARED_2', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_ARCHVG_SHARED_3', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_BTFS1REDOVG1_SHARED_1', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_BTFS1REDOVG2_SHARED_2', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT_3_4_REPO_CAAVG_SHARED_1', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT3_ROOT_1', '', ['pandbt3'], ''),
              ('PANDBT3_ROOT_2', '', ['pandbt3'], ''),
              ('PANDBT3_ROOT_3', '', ['pandbt3'], ''),
              ('Pandbt_3_4_Shared_ORAEX_1', '', ['pandbt3', 'pandbt4'], ''),
              ('Pandbt_3_4_Shared_ORAEX_2', '', ['pandbt3', 'pandbt4'], ''),
              ('Pandbt_3_4_Shared_ORAEX_3', '', ['pandbt3', 'pandbt4'], ''),
              ('Pandbt_3_4_Shared_ORAEX_4', '', ['pandbt3', 'pandbt4'], ''),
              ('Pandbt_3_4_Shared_ORAEX_5', '', ['pandbt3', 'pandbt4'], ''),
              ('PANDBT4_ROOT_1', '', ['pandbt4'], ''),
              ('PANDBT4_ROOT_2', '', ['pandbt4'], ''),
              ('PANDBT4_ROOT_3', '', ['pandbt4'], ''),
              ('pandbtdg1_0', '', ['pandbtdg1'], ''),
              ('pandbtdg1_1', '', ['pandbtdg1'], ''),
              ('pandbtdg1_2', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_1', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_2', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_3', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_4', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_5', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_6', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_7', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_8', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_9', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_10', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_11', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_12', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_13', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_14', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_15', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_16', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_17', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_18', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_20', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_21', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_22', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_23', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_24', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_25', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_26', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_27', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_28', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_29', '', ['pandbtdg1'], ''),
              ('pandbtdg1_dg_30', '', ['pandbtdg1'], ''),
              ('panddb01_0', '', ['panddb01'], ''),
              ('panddb01_1', '', ['panddb01'], ''),
              ('panddb01_2', '', ['panddb01'], ''),
              ('panddb01_3', '', ['panddb01'], ''),
              ('panddb01_4', '', ['panddb01'], ''),
              ('panddb01_5', '', ['panddb01'], ''),
              ('panddb01_6', '', ['panddb01'], ''),
              ('panddb01_7', '', ['panddb01'], ''),
              ('panddb01_8', '', ['panddb01'], ''),
              ('panddb01_9', '', ['panddb01'], ''),
              ('panddb01_10', '', ['panddb01'], ''),
              ('panddb01_11', '', ['panddb01'], ''),
              ('panddb01_12', '', ['panddb01'], ''),
              ('panddb01_13', '', ['panddb01'], ''),
              ('panddb01_14', '', ['panddb01'], ''),
              ('panddb01_15', '', ['panddb01'], ''),
              ('panddb01_16', '', ['panddb01'], ''),
              ('panddb01_17', '', ['panddb01'], ''),
              ('panddb01_18', '', ['panddb01'], ''),
              ('panddb01_19', '', ['panddb01'], ''),
              ('panddb01_20', '', ['panddb01'], ''),
              ('panddb02_0', '', ['panddb02'], ''),
              ('panddb02_1', '', ['panddb02'], ''),
              ('panddb02_2', '', ['panddb02'], ''),
              ('pandmfs1_0', '', ['pandmfs1'], ''),
              ('pandmfs1_1', '', ['pandmfs1'], ''),
              ('pandmfs1_2', '', ['pandmfs1'], ''),
              ('pandmfs_1_2_HA', '', ['pandmfs1', 'pandmfs2'], ''),
              ('pandmfs_1_2_shared_1', '', ['pandmfs1', 'pandmfs2'], ''),
              ('pandmfs_1_2_shared_17', '', ['pandmfs1', 'pandmfs2'], ''),
              ('pandmfs_1_2_shared_16', '', ['pandmfs1', 'pandmfs2'], ''),
              ('pandmfs_1_2_shared_15', '', ['pandmfs1', 'pandmfs2'], ''),
              ('pandmfs_1_2_shared_14', '', ['pandmfs1', 'pandmfs2'], ''),
              ('pandmfs_1_2_shared_12', '', ['pandmfs1', 'pandmfs2'], ''),
              ('pandmfs_1_2_shared_11', '', ['pandmfs1', 'pandmfs2'], ''),
              ('pandmfs_1_2_shared_8', '', ['pandmfs1', 'pandmfs2'], ''),
              ('pandmfs_1_2_shared_7', '', ['pandmfs1', 'pandmfs2'], ''),
              ('pandmfs_1_2_shared_5', '', ['pandmfs1', 'pandmfs2'], ''),
              ('pandmfs_1_2_shared_4', '', ['pandmfs1', 'pandmfs2'], ''),
              ('pandmfs_1_2_shared_3', '', ['pandmfs1', 'pandmfs2'], ''),
              ('pandmfs_1_2_shared_2', '', ['pandmfs1', 'pandmfs2'], ''),
              ('pandmfs_1_2_shared_18', '', ['pandmfs1', 'pandmfs2'], ''),
              ('pandmfs_1_2_shared_19', '', ['pandmfs1', 'pandmfs2'], ''),
              ('pandmfs10_01', '', ['pandmfs10'], ''),
              ('pandmfs10_02', '', ['pandmfs10'], ''),
              ('pandmfs10_03', '', ['pandmfs10'], ''),
              ('pandmfs10_04', '', ['pandmfs10'], ''),
              ('pandmfs10_05', '', ['pandmfs10'], ''),
              ('pandmfs10_06', '', ['pandmfs10'], ''),
              ('pandmfs10_07', '', ['pandmfs10'], ''),
              ('pandmfs10_08', '', ['pandmfs10'], ''),
              ('pandmfs10_asm0', '', ['pandmfs10'], ''),
              ('pandmfs10_asm1', '', ['pandmfs10'], ''),
              ('pandmfs10_asm2', '', ['pandmfs10'], ''),
              ('pandmfs10_asm3', '', ['pandmfs10'], ''),
              ('pandmfs10_asm4', '', ['pandmfs10'], ''),
              ('pandmfs10_asm5', '', ['pandmfs10'], ''),
              ('pandmfs10_asm6', '', ['pandmfs10'], ''),
              ('pandmfs2_0', '', ['pandmfs2'], ''),
              ('pandmfs2_1', '', ['pandmfs2'], ''),
              ('pandmfs2_2', '', ['pandmfs2'], ''),
              ('PANDMFS3_ROOT_1', '', ['pandmfs3'], ''),
              ('PANDMFS3_ROOT_2', '', ['pandmfs3'], ''),
              ('PANDMFS3_ROOT_3', '', ['pandmfs3'], ''),
              ('PANDMFS_3_4_ORA1VG_SHARED_1', '', ['pandmfs3', 'pandmfs4'], ''),
              ('PANDMFS_3_4_ORA1VG_SHARED_2', '', ['pandmfs3', 'pandmfs4'], ''),
              ('PANDMFS_3_4_ORA1VG_SHARED_3', '', ['pandmfs3', 'pandmfs4'], ''),
              ('PANDMFS_3_4_ORA1VG_SHARED_4', '', ['pandmfs3', 'pandmfs4'], ''),
              ('PANDMFS_3_4_ORA1VG_SHARED_5', '', ['pandmfs3', 'pandmfs4'], ''),
              ('PANDMFS_3_4_ORA1VG_SHARED_6', '', ['pandmfs3', 'pandmfs4'], ''),
              ('PANDMFS_3_4_ORA1VG_SHARED_7', '', ['pandmfs3', 'pandmfs4'], ''),
              ('PANDMFS_3_4_ORA1VG_SHARED_8', '', ['pandmfs3', 'pandmfs4'], ''),
              ('PANDMFS_3_4_ARCHVG_SHARED_1', '', ['pandmfs3', 'pandmfs4'], ''),
              ('PANDMFS_3_4_ARCHVG_SHARED_2', '', ['pandmfs3', 'pandmfs4'], ''),
              ('PANDMFS_3_4_MFS1REDOVG1_SHARED_1', '', ['pandmfs3', 'pandmfs4'], ''),
              ('PANDMFS_3_4_MFS1REDOVG2_SHARED_2', '', ['pandmfs3', 'pandmfs4'], ''),
              ('PANDMFS_3_4_REPO_CAAVG_SHARED_1', '', ['pandmfs3', 'pandmfs4'], ''),
              ('tandmfs20_clone0', '', ['pandmfs3'], ''),
              ('tandmfs20_clone2', '', ['pandmfs3'], ''),
              ('tandmfs20_clone1', '', ['pandmfs3'], ''),
              ('PANDMFS4_ROOT_1', '', ['pandmfs4'], ''),
              ('PANDMFS4_ROOT_2', '', ['pandmfs4'], ''),
              ('PANDMFS4_ROOT_3', '', ['pandmfs4'], ''),
              ('tandmfs20_clone_root0', '', ['pandmfs4'], ''),
              ('tandmfs20_clone_root1', '', ['pandmfs4'], ''),
              ('tandmfs20_clone_root2', '', ['pandmfs4'], ''),
              ('pandmfsdg1_0', '', ['pandmfsdg1'], ''),
              ('pandmfsdg1_1', '', ['pandmfsdg1'], ''),
              ('pandmfsdg1_2', '', ['pandmfsdg1'], ''),
              ('pandmfs_dg_mast_1', '', ['pandmfsdg1'], ''),
              ('pandmfs_dg_mast_2', '', ['pandmfsdg1'], ''),
              ('pandmfs_dg_mast_3', '', ['pandmfsdg1'], ''),
              ('pandmfs_dg_mast_4', '', ['pandmfsdg1'], ''),
              ('pandmfs_dg_mast_5', '', ['pandmfsdg1'], ''),
              ('pandmfs_dg_mast_7', '', ['pandmfsdg1'], ''),
              ('pandmfs_dg_mast_8', '', ['pandmfsdg1'], ''),
              ('pandmfs_dg_mast_11', '', ['pandmfsdg1'], ''),
              ('pandmfs_dg_mast_12', '', ['pandmfsdg1'], ''),
              ('pandmfs_dg_mast_14', '', ['pandmfsdg1'], ''),
              ('pandmfs_dg_mast_15', '', ['pandmfsdg1'], ''),
              ('pandmfs_dg_mast_16', '', ['pandmfsdg1'], ''),
              ('pandmfs_dg_mast_17', '', ['pandmfsdg1'], ''),
              ('pandnim01_3', '', ['pandnim01'], ''),
              ('pandnim01_0', '', ['pandnim01'], ''),
              ('pandnim01_1', '', ['pandnim01'], ''),
              ('pandnim01_2', '', ['pandnim01'], ''),
              ('pandnim01_4', '', ['pandnim01'], ''),
              ('pandnim01_5', '', ['pandnim01'], ''),
              ('pandnim01_6', '', ['pandnim01'], ''),
              ('pandnim01_7', '', ['pandnim01'], ''),
              ('pandnim01_8', '', ['pandnim01'], ''),
              ('pandnim01_9', '', ['pandnim01'], ''),
              ('pandnim01_10', '', ['pandnim01'], ''),
              ('pandnim01_11', '', ['pandnim01'], ''),
              ('Pandnim01_13_1', '', ['pandnim01'], ''),
              ('Pandnim01_13_2', '', ['pandnim01'], ''),
              ('pandnim01_14', '', ['pandnim01'], ''),
              ('pandsps1_0', '', ['pandsps1'], ''),
              ('pandsps1_1', '', ['pandsps1'], ''),
              ('pandsps1_2', '', ['pandsps1'], ''),
              ('pandsps_1_2_HA', '', ['pandsps1', 'pandsps2'], ''),
              ('pandsps_1_2_shared_1', '', ['pandsps1', 'pandsps2'], ''),
              ('pandsps_1_2_shared_2', '', ['pandsps1', 'pandsps2'], ''),
              ('pandsps_1_2_shared_3', '', ['pandsps1', 'pandsps2'], ''),
              ('pandsps_1_2_shared_4', '', ['pandsps1', 'pandsps2'], ''),
              ('pandsps_1_2_shared_6', '', ['pandsps1', 'pandsps2'], ''),
              ('pandsps_1_2_shared_7', '', ['pandsps1', 'pandsps2'], ''),
              ('pandsps_1_2_shared_11', '', ['pandsps1', 'pandsps2'], ''),
              ('pandsps_1_2_shared_12', '', ['pandsps1', 'pandsps2'], ''),
              ('pandsps_1_2_shared_13', '', ['pandsps1', 'pandsps2'], ''),
              ('pandsps_1_2_shared_14', '', ['pandsps1', 'pandsps2'], ''),
              ('pandsps_1_2_shared_15', '', ['pandsps1', 'pandsps2'], ''),
              ('pandsps_1_2_shared_16', '', ['pandsps1', 'pandsps2'], ''),
              ('pandsps_1_2_shared_17', '', ['pandsps1', 'pandsps2'], ''),
              ('pandsps_1_2_shared_18', '', ['pandsps1', 'pandsps2'], ''),
              ('pandsps_1_2_shared_19', '', ['pandsps1', 'pandsps2'], ''),
              ('pandsps_1_2_shared_20', '', ['pandsps1', 'pandsps2'], ''),
              ('pandsps_1_2_shared_21', '', ['pandsps1', 'pandsps2'], ''),
              ('pandsps2_0', '', ['pandsps2'], ''),
              ('pandsps2_1', '', ['pandsps2'], ''),
              ('pandsps2_2', '', ['pandsps2'], ''),
              ('PANDSPS_3_4_ROOT_1', '', ['pandsps3'], ''),
              ('PANDSPS_3_4_ROOT_2', '', ['pandsps3'], ''),
              ('PANDSPS_3_4_ROOT_3', '', ['pandsps3'], ''),
              ('PANDSPS_3_4_ORA1VG_SHARED_1', '', ['pandsps3', 'pandsps4'], ''),
              ('PANDSPS_3_4_ORA1VG_SHARED_2', '', ['pandsps3', 'pandsps4'], ''),
              ('PANDSPS_3_4_ORA1VG_SHARED_3', '', ['pandsps3', 'pandsps4'], ''),
              ('PANDSPS_3_4_ORA1VG_SHARED_4', '', ['pandsps3', 'pandsps4'], ''),
              ('PANDSPS_3_4_ORA1VG_SHARED_5', '', ['pandsps3', 'pandsps4'], ''),
              ('PANDSPS_3_4_ORA1VG_SHARED_6', '', ['pandsps3', 'pandsps4'], ''),
              ('PANDSPS_3_4_ORA1VG_SHARED_7', '', ['pandsps3', 'pandsps4'], ''),
              ('PANDSPS_3_4_ORA1VG_SHARED_8', '', ['pandsps3', 'pandsps4'], ''),
              ('PANDSPS_3_4_ORA1VG_SHARED_9', '', ['pandsps3', 'pandsps4'], ''),
              ('PANDSPS_3_4_ARCHVG_SHARED_1', '', ['pandsps3', 'pandsps4'], ''),
              ('PANDSPS_3_4_ARCHVG_SHARED_2', '', ['pandsps3', 'pandsps4'], ''),
              ('PANDSPS_3_4_SPS1REDOVG1_SHARED_1', '', ['pandsps3', 'pandsps4'], ''),
              ('PANDSPS_3_4_SPS1REDOVG2_SHARED_2', '', ['pandsps3', 'pandsps4'], ''),
              ('PANDSPS_3_4_REPO_CAAVG_SHARED_1', '', ['pandsps3', 'pandsps4'], ''),
              ('PANDSPS3_ROOT_1', '', ['pandsps3'], ''),
              ('PANDSPS3_ROOT_2', '', ['pandsps3'], ''),
              ('PANDSPS3_ROOT_3', '', ['pandsps3'], ''),
              ('PANDSPS4_ROOT_0', '', ['pandsps4'], ''),
              ('PANDSPS4_ROOT_1', '', ['pandsps4'], ''),
              ('PANDSPS4_ROOT_2', '', ['pandsps4'], ''),
              ('pandspsa1_0', '', ['pandspsa1'], ''),
              ('pandspsa1_1', '', ['pandspsa1'], ''),
              ('pandspsa1_2', '', ['pandspsa1'], ''),
              ('pandspsa1_2_HA', '', ['pandspsa1', 'pandspsa2'], ''),
              ('pandspsa1_2_DATA', '', ['pandspsa1', 'pandspsa2'], ''),
              ('pandspsa2_0', '', ['pandspsa2'], ''),
              ('pandspsa2_1', '', ['pandspsa2'], ''),
              ('pandspsa2_2', '', ['pandspsa2'], ''),
              ('pandspsdg1_0', '', ['pandspsdg1'], ''),
              ('pandspsdg1_1', '', ['pandspsdg1'], ''),
              ('pandspsdg1_2', '', ['pandspsdg1'], ''),
              ('pandspsdg1_dg_1', '', ['pandspsdg1'], ''),
              ('pandspsdg1_dg_2', '', ['pandspsdg1'], ''),
              ('pandspsdg1_dg_3', '', ['pandspsdg1'], ''),
              ('pandspsdg1_dg_4', '', ['pandspsdg1'], ''),
              ('pandspsdg1_dg_6', '', ['pandspsdg1'], ''),
              ('pandspsdg1_dg_7', '', ['pandspsdg1'], ''),
              ('pandspsdg1_dg_11', '', ['pandspsdg1'], ''),
              ('pandspsdg1_dg_12', '', ['pandspsdg1'], ''),
              ('pandspsdg1_dg_13', '', ['pandspsdg1'], ''),
              ('pandspsdg1_dg_14', '', ['pandspsdg1'], ''),
              ('pandspsdg1_dg_15', '', ['pandspsdg1'], ''),
              ('pandspsdg1_dg_16', '', ['pandspsdg1'], ''),
              ('pandspsdg1_dg_17', '', ['pandspsdg1'], ''),
              ('pandspsdg1_dg_18', '', ['pandspsdg1'], ''),
              ('pandspsdg1_dg_19', '', ['pandspsdg1'], ''),
              ('pandvio01a_root_1', '', ['pandvio01a'], ''),
              ('pandvio01a_root_2', '', ['pandvio01a'], ''),
              ('pandvio01b_root_1', '', ['pandvio01b'], ''),
              ('pandvio01b_root_2', '', ['pandvio01b'], ''),
              ('pandvio02a_root_1', '', ['pandvio02a'], ''),
              ('pandvio02a_root_2', '', ['pandvio02a'], ''),
              ('pandvio02b_root_1', '', ['pandvio02b'], ''),
              ('pandvio02b_root_2', '', ['pandvio02b'], ''),
              ('pandvio03a_root_0', '', ['pandvio03a'], ''),
              ('pandvio03a_root_1', '', ['pandvio03a'], ''),
              ('pandvio03b_root_0', '', ['pandvio03b'], ''),
              ('pandvio03b_root_1', '', ['pandvio03b'], ''),
              ('pandvio04a_root_0', '', ['pandvio04a'], ''),
              ('pandvio04a_root_1', '', ['pandvio04a'], ''),
              ('pandvio04b_root_0', '', ['pandvio04b'], ''),
              ('pandvio04b_root_1', '', ['pandvio04b'], ''),
              ('pandvio5a_0', '', ['pandvio05a'], ''),
              ('pandvio5a_1', '', ['pandvio05a'], ''),
              ('pandvio5a_2', '', ['pandvio05a'], ''),
              ('pandvio5a_3', '', ['pandvio05a'], ''),
              ('pandvio5b_0', '', ['pandvio05b'], ''),
              ('pandvio5b_1', '', ['pandvio05b'], ''),
              ('pandvio5b_2', '', ['pandvio05b'], ''),
              ('pandvio6a_0', '', ['pandvio06a'], ''),
              ('pandvio6a_1', '', ['pandvio06a'], ''),
              ('pandvio6a_2', '', ['pandvio06a'], ''),
              ('pandvio6b_0', '', ['pandvio06b'], ''),
              ('pandvio6b_1', '', ['pandvio06b'], ''),
              ('pandvio6b_2', '', ['pandvio06b'], ''),
              ('pandvio7a_0', '', ['pandvio07a'], ''),
              ('pandvio7a_1', '', ['pandvio07a'], ''),
              ('pandvio7a_2', '', ['pandvio07a'], ''),
              ('pandvio7b_0', '', ['pandvio07b'], ''),
              ('pandvio7b_1', '', ['pandvio07b'], ''),
              ('pandvio7b_2', '', ['pandvio07b'], ''),
              ('pandvio8a_0', '', ['pandvio08a'], ''),
              ('pandvio8a_1', '', ['pandvio08a'], ''),
              ('pandvio8b_0', '', ['pandvio08b'], ''),
              ('pandvio8b_1', '', ['pandvio08b'], ''),
              ('pandvio9a_0', '', ['pandvio09a'], ''),
              ('pandvio9a_1', '', ['pandvio09a'], ''),
              ('pandvio9b_0', '', ['pandvio09b'], ''),
              ('pandvio9b_1', '', ['pandvio09b'], ''),
              ('pandvio10a_root_1', '', ['pandvio10a'], ''),
              ('pandvio10a_root_2', '', ['pandvio10a'], ''),
              ('pandvio10b_root_1', '', ['pandvio10b'], ''),
              ('pandvio10b_root_2', '', ['pandvio10b'], ''),
              ('ADC-Data01', '', ['pen_andesx_vm03', 'pen_andesx_vm04'], ''),
              ('ADC-Data02', '', ['pen_andesx_vm03', 'pen_andesx_vm04'], ''),
              ('ADC-Data03', '', ['pen_andesx_vm03', 'pen_andesx_vm04'], ''),
              ('Andesx-DS01', '', ['pen_andesx_vm03', 'pen_andesx_vm04'], ''),
              ('Andesx-DS02', '', ['pen_andesx_vm03', 'pen_andesx_vm04'], ''),
              ('Andesx-DS03', '', ['pen_andesx_vm03', 'pen_andesx_vm04'], ''),
              ('RHEL-Networker01', '', ['pen_andesx_vm03', 'pen_andesx_vm04'], ''),
              ('pla-wanoemcr01_02_data_1', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_300GB_1', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_300GB_2', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_300GB_3', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_300GB_4', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_300GB_5', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_250GB1', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_250GB2', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_250GB3', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_250GB4', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_250GB5', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_250GB6', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_250GB7', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_250GB8', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_250GB9', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_250GB10', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_5GB1', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_5GB2', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_5GB3', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_5GB4', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_5GB5', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_5GB6', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_5GB7', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_5GB8', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_5GB9', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_5GB10', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_5GB11', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_5GB12', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_5GB13', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_5GB14', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_5GB15', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_5GB16', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_5GB17', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_5GB18', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_5GB19', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_5GB20', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_501', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_502', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_503', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_504', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_data_2', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_data_3', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_data_4', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_data_5', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_data_6', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_data_7', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_data_8', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_FRA_1', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_FRA_2', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_FRA_3', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_FRA_4', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_redo_1', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_redo_2', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_redo_3', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_redo_4', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_redo_5', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_redo_6', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_redo_7', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_redo_8', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_redo_9', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('pla-wanoemcr01_02_redo_10', '', ['pla-wanoemcr01', 'pla-wanoemcr02'], ''),
              ('tandbt1_0', '', ['tandbt1'], ''),
              ('tandbt1_1', '', ['tandbt1'], ''),
              ('tandbt1_2', '', ['tandbt1'], ''),
              ('tandbt1_db_1', '', ['tandbt1'], ''),
              ('tandbt1_db_2', '', ['tandbt1'], ''),
              ('tandbt1_db_3', '', ['tandbt1'], ''),
              ('tandbt1_db_4', '', ['tandbt1'], ''),
              ('tandbt1_db_5', '', ['tandbt1'], ''),
              ('tandbt1_db_6', '', ['tandbt1'], ''),
              ('tandbt1_db_7', '', ['tandbt1'], ''),
              ('tandbt1_db_8', '', ['tandbt1'], ''),
              ('tandbt1_db_9', '', ['tandbt1'], ''),
              ('tandbt1_db_10', '', ['tandbt1'], ''),
              ('tandbt1_db_11', '', ['tandbt1'], ''),
              ('tandbt1_db_12', '', ['tandbt1'], ''),
              ('tandbt1_db_13', '', ['tandbt1'], ''),
              ('tandbt1_db_14', '', ['tandbt1'], ''),
              ('tandbt1_db_15', '', ['tandbt1'], ''),
              ('tandbt1_db_16', '', ['tandbt1'], ''),
              ('tandbt1_db_17', '', ['tandbt1'], ''),
              ('tandbt1_db_18', '', ['tandbt1'], ''),
              ('tandbt1_db_20', '', ['tandbt1'], ''),
              ('tandbt1_db_21', '', ['tandbt1'], ''),
              ('tandbt1_db_22', '', ['tandbt1'], ''),
              ('tandbt1_db_23', '', ['tandbt1'], ''),
              ('tandbt1_db_24', '', ['tandbt1'], ''),
              ('tandbt1_db_25', '', ['tandbt1'], ''),
              ('tandbt1_db_26', '', ['tandbt1'], ''),
              ('tandbt1_db_27', '', ['tandbt1'], ''),
              ('tandbt1_db_28', '', ['tandbt1'], ''),
              ('tandbt1_db_29', '', ['tandbt1'], ''),
              ('tandbt1_db_30', '', ['tandbt1'], ''),
              ('tandbt20_0', '', ['tandbt20'], ''),
              ('tandbt20_1', '', ['tandbt20'], ''),
              ('tandbt20_2', '', ['tandbt20'], ''),
              ('tandbt20_data_1', '', ['tandbt20'], ''),
              ('tandbt20_data_2', '', ['tandbt20'], ''),
              ('tandbt20_data_3', '', ['tandbt20'], ''),
              ('tandbt20_data_4', '', ['tandbt20'], ''),
              ('tandbt20_data_5', '', ['tandbt20'], ''),
              ('tandbt20_data_6', '', ['tandbt20'], ''),
              ('tandbt20_data_7', '', ['tandbt20'], ''),
              ('tandbt20_data_8', '', ['tandbt20'], ''),
              ('tandbt20_data_9', '', ['tandbt20'], ''),
              ('tandbt20_data_10', '', ['tandbt20'], ''),
              ('tandbt20_data_11', '', ['tandbt20'], ''),
              ('tandbt20_data_12', '', ['tandbt20'], ''),
              ('tandbt20_data_13', '', ['tandbt20'], ''),
              ('tandbt20_data_14', '', ['tandbt20'], ''),
              ('tandbt20_data_15', '', ['tandbt20'], ''),
              ('tandbt20_data_16', '', ['tandbt20'], ''),
              ('tandbt20_data_17', '', ['tandbt20'], ''),
              ('tandbt20_data_18', '', ['tandbt20'], ''),
              ('tandbt20_data_19', '', ['tandbt20'], ''),
              ('tandbt20_data_20', '', ['tandbt20'], ''),
              ('tandbt20_data_21', '', ['tandbt20'], ''),
              ('tandbt20_data_22', '', ['tandbt20'], ''),
              ('tandbt20_data_23', '', ['tandbt20'], ''),
              ('tandbt20_data_24', '', ['tandbt20'], ''),
              ('tandbt20_data_25', '', ['tandbt20'], ''),
              ('tandbt20_data_26', '', ['tandbt20'], ''),
              ('tandbt20_data_27', '', ['tandbt20'], ''),
              ('tandbt20_data_28', '', ['tandbt20'], ''),
              ('tandbt20_data_29', '', ['tandbt20'], ''),
              ('tandbt20_data_30', '', ['tandbt20'], ''),
              ('tandbt20_data_31', '', ['tandbt20'], ''),
              ('tandbt20_data_32', '', ['tandbt20'], ''),
              ('tandbt20_data_33', '', ['tandbt20'], ''),
              ('tandbt20_data_34', '', ['tandbt20'], ''),
              ('tandbt20_data_35', '', ['tandbt20'], ''),
              ('tandbt20_data_36', '', ['tandbt20'], ''),
              ('tandbt20_data_37', '', ['tandbt20'], ''),
              ('tandbt_clone_root2', '', ['tandbt20'], ''),
              ('tandbt_clone_root1', '', ['tandbt20'], ''),
              ('tandbt_clone_root0', '', ['tandbt20'], ''),
              ('tandmfs1_0', '', ['tandmfs1'], ''),
              ('tandmfs1_1', '', ['tandmfs1'], ''),
              ('tandmfs1_2', '', ['tandmfs1'], ''),
              ('pandmfs_dg_mast_1_01', '', ['tandmfs1'], ''),
              ('pandmfs_dg_mast_2_01', '', ['tandmfs1'], ''),
              ('pandmfs_dg_mast_3_01', '', ['tandmfs1'], ''),
              ('pandmfs_dg_mast_4_01', '', ['tandmfs1'], ''),
              ('pandmfs_dg_mast_5_01', '', ['tandmfs1'], ''),
              ('pandmfs_dg_mast_7_01', '', ['tandmfs1'], ''),
              ('pandmfs_dg_mast_8_01', '', ['tandmfs1'], ''),
              ('pandmfs_dg_mast_11_01', '', ['tandmfs1'], ''),
              ('pandmfs_dg_mast_12_01', '', ['tandmfs1'], ''),
              ('pandmfs_dg_mast_14_01', '', ['tandmfs1'], ''),
              ('pandmfs_dg_mast_15_01', '', ['tandmfs1'], ''),
              ('pandmfs_dg_mast_16_01', '', ['tandmfs1'], ''),
              ('pandmfs_dg_mast_17_01', '', ['tandmfs1'], ''),
              ('tandmfs2_0', '', ['tandmfs2'], ''),
              ('tandmfs2_1', '', ['tandmfs2'], ''),
              ('tandmfs2_2', '', ['tandmfs2'], ''),
              ('tandmfs2_3', '', ['tandmfs2'], ''),
              ('tandmfs2_4', '', ['tandmfs2'], ''),
              ('tandmfs2_5', '', ['tandmfs2'], ''),
              ('tandmfs2_6', '', ['tandmfs2'], ''),
              ('tandmfs2_7', '', ['tandmfs2'], ''),
              ('tandmfs2_asm0', '', ['tandmfs2'], ''),
              ('tandmfs2_asm1', '', ['tandmfs2'], ''),
              ('tandmfs2_asm2', '', ['tandmfs2'], ''),
              ('tandmfs2_asm3', '', ['tandmfs2'], ''),
              ('tandmfs2_asm4', '', ['tandmfs2'], ''),
              ('tandmfs2_asm5', '', ['tandmfs2'], ''),
              ('tandmfs2_asm6', '', ['tandmfs2'], ''),
              ('tandmfs20_0', '', ['tandmfs20'], ''),
              ('tandmfs20_1', '', ['tandmfs20'], ''),
              ('tandmfs20_2', '', ['tandmfs20'], ''),
              ('tandmfs20_data_1', '', ['tandmfs20'], ''),
              ('tandmfs20_data_2', '', ['tandmfs20'], ''),
              ('tandmfs20_data_3', '', ['tandmfs20'], ''),
              ('tandmfs20_data_4', '', ['tandmfs20'], ''),
              ('tandmfs20_data_5', '', ['tandmfs20'], ''),
              ('tandmfs20_data_7', '', ['tandmfs20'], ''),
              ('tandmfs20_data_8', '', ['tandmfs20'], ''),
              ('tandmfs20_data_11', '', ['tandmfs20'], ''),
              ('tandmfs20_data_12', '', ['tandmfs20'], ''),
              ('tandmfs20_data_14', '', ['tandmfs20'], ''),
              ('tandmfs20_data_15', '', ['tandmfs20'], ''),
              ('tandmfs20_data_16', '', ['tandmfs20'], ''),
              ('tandmfs20_data_17', '', ['tandmfs20'], ''),
              ('tandmfs20_data_18', '', ['tandmfs20'], ''),
              ('tandmfs20_data_19', '', ['tandmfs20'], ''),
              ('tandsmfs_clone_root0', '', ['tandmfs20'], ''),
              ('tandsmfs_clone_root1', '', ['tandmfs20'], ''),
              ('tandmfs_clone_root0', '', ['tandmfs20'], ''),
              ('tandmfs_clone_root1', '', ['tandmfs20'], ''),
              ('tandmfs_clone_root2', '', ['tandmfs20'], ''),
              ('tandsps1_0', '', ['tandsps1'], ''),
              ('tandsps1_1', '', ['tandsps1'], ''),
              ('tandsps1_2', '', ['tandsps1'], ''),
              ('tandsps_1_2_shared_1', '', ['tandsps1', 'tandsps2'], ''),
              ('tandsps_1_2_shared_2', '', ['tandsps1', 'tandsps2'], ''),
              ('tandsps_1_2_shared_3', '', ['tandsps1', 'tandsps2'], ''),
              ('tandsps_1_2_shared_4', '', ['tandsps1', 'tandsps2'], ''),
              ('tandsps_1_2_shared_5', '', ['tandsps1', 'tandsps2'], ''),
              ('tandsps_1_2_shared_6', '', ['tandsps1', 'tandsps2'], ''),
              ('tandsps_1_2_shared_7', '', ['tandsps1', 'tandsps2'], ''),
              ('tandsps_1_2_shared_8', '', ['tandsps1', 'tandsps2'], ''),
              ('tandsps_1_2_shared_9', '', ['tandsps1', 'tandsps2'], ''),
              ('tandsps_1_2_shared_10', '', ['tandsps1', 'tandsps2'], ''),
              ('tandsps_1_2_shared_11', '', ['tandsps1', 'tandsps2'], ''),
              ('tandsps_1_2_shared_12', '', ['tandsps1', 'tandsps2'], ''),
              ('tandsps_1_2_shared_13', '', ['tandsps1', 'tandsps2'], ''),
              ('tandsps_1_2_shared_14', '', ['tandsps1', 'tandsps2'], ''),
              ('tandsps_1_2_shared_15', '', ['tandsps1', 'tandsps2'], ''),
              ('tandsps_1_2_HA', '', ['tandsps1', 'tandsps2'], ''),
              ('tandsps2_1', '', ['tandsps2'], ''),
              ('tandsps2_2', '', ['tandsps2'], ''),
              ('tandsps2_0', '', ['tandsps2'], ''),
              ('tandsps20_0', '', ['tandsps20'], ''),
              ('tandsps20_1', '', ['tandsps20'], ''),
              ('tandsps20_2', '', ['tandsps20'], ''),
              ('tandsps20_21_HA', '', ['tandsps20', 'tandsps21'], ''),
              ('tandsps20_21_shared_1', '', ['tandsps20', 'tandsps21'], ''),
              ('tandsps20_21_shared_2', '', ['tandsps20', 'tandsps21'], ''),
              ('tandsps20_21_shared_3', '', ['tandsps20', 'tandsps21'], ''),
              ('tandsps20_21_shared_4', '', ['tandsps20', 'tandsps21'], ''),
              ('tandsps20_21_shared_6', '', ['tandsps20', 'tandsps21'], ''),
              ('tandsps20_21_shared_7', '', ['tandsps20', 'tandsps21'], ''),
              ('tandsps20_21_shared_11', '', ['tandsps20', 'tandsps21'], ''),
              ('tandsps20_21_shared_12', '', ['tandsps20', 'tandsps21'], ''),
              ('tandsps20_21_shared_13', '', ['tandsps20', 'tandsps21'], ''),
              ('tandsps20_21_shared_14', '', ['tandsps20', 'tandsps21'], ''),
              ('tandsps20_21_shared_15', '', ['tandsps20', 'tandsps21'], ''),
              ('tandsps20_21_shared_16', '', ['tandsps20', 'tandsps21'], ''),
              ('tandsps20_21_shared_17', '', ['tandsps20', 'tandsps21'], ''),
              ('tandsps20_21_shared_18', '', ['tandsps20', 'tandsps21'], ''),
              ('tandsps20_21_shared_19', '', ['tandsps20', 'tandsps21'], ''),
              ('tandsps20_21_shared_20', '', ['tandsps20', 'tandsps21'], ''),
              ('tandsps20_21_shared_21', '', ['tandsps20', 'tandsps21'], ''),
              ('tandsps_clone_root0', '', ['tandsps20'], ''),
              ('tandsps_clone_root1', '', ['tandsps20'], ''),
              ('tandsps_clone_root2', '', ['tandsps20'], ''),
              ('tandsps21_0', '', ['tandsps21'], ''),
              ('tandsps21_1', '', ['tandsps21'], ''),
              ('tandsps21_2', '', ['tandsps21'], ''),
              ('pconbt1_2_archvg_dt1', '', ['tconbt20'], ''),
              ('pconbt1_2_archvg_dt2', '', ['tconbt20'], ''),
              ('pconbt1_2_btfs1redovg_dt1', '', ['tconbt20'], ''),
              ('pconbt1_2_btfs1redovg_dt2', '', ['tconbt20'], ''),
              ('pconbt1_2_caavg_dt', '', ['tconbt20'], ''),
              ('pconbt1_2_oraclevg_dt_1', '', ['tconbt20'], ''),
              ('pconbt1_2_oraclevg_dt_2', '', ['tconbt20'], ''),
              ('pconbt1_2_oraclevg_dt_3', '', ['tconbt20'], ''),
              ('pconbt1_2_oraclevg_dt_4', '', ['tconbt20'], ''),
              ('pconbt1_2_oraclevg_dt_5', '', ['tconbt20'], ''),
              ('pconbt1_2_oraclevg_dt_6', '', ['tconbt20'], ''),
              ('pconbt1_2_oraclevg_dt_7', '', ['tconbt20'], ''),
              ('pconbt1_2_oraclevg_dt_8', '', ['tconbt20'], ''),
              ('pconbt1_2_oraclevg_dt_9', '', ['tconbt20'], ''),
              ('pconbt1_2_oraclevg_dt_10', '', ['tconbt20'], ''),
              ('pconbt1_2_oraclevg_dt_11', '', ['tconbt20'], ''),
              ('pconbt1_2_oraclevg_dt_12', '', ['tconbt20'], ''),
              ('pconbt1_2_oraclevg_dt_13', '', ['tconbt20'], ''),
              ('pconbt1_2_oraclevg_dt_14', '', ['tconbt20'], ''),
              ('pconbt1_rootvg_dt_1', '', ['tconbt20'], ''),
              ('pconbt1_rootvg_dt_2', '', ['tconbt20'], ''),
              ('pconbt1_rootvg_dt_3', '', ['tconbt20'], ''),
              ('tconbt20_vol1', '', ['tconbt20'], ''),
              ('pconmfs1_2_archvg_dt_1', '', ['tconmfs20'], ''),
              ('pconmfs1_2_caavg_dt', '', ['tconmfs20'], ''),
              ('pconmfs1_2_mfs1redovg_dt_1', '', ['tconmfs20'], ''),
              ('pconmfs1_2_mfs1redovg_dt_2', '', ['tconmfs20'], ''),
              ('pconmfs1_2_ora1vg_dt1', '', ['tconmfs20'], ''),
              ('pconmfs1_2_ora1vg_dt2', '', ['tconmfs20'], ''),
              ('pconmfs1_2_ora1vg_dt3', '', ['tconmfs20'], ''),
              ('pconmfs1_2_ora1vg_dt4', '', ['tconmfs20'], ''),
              ('pconmfs1_2_ora1vg_dt5', '', ['tconmfs20'], ''),
              ('pconmfs1_2_ora1vg_dt6', '', ['tconmfs20'], ''),
              ('pconmfs1_2_ora1vg_dt7', '', ['tconmfs20'], ''),
              ('pconmfs1_root_sysvg_dt_1', '', ['tconmfs20'], ''),
              ('pconmfs1_root_sysvg_dt_2', '', ['tconmfs20'], ''),
              ('pconmfs1_root_sysvg_dt_3', '', ['tconmfs20'], ''),
              ('pconsps1_2_archvg_dt_1', '', ['tconsps20', 'tconsps21'], ''),
              ('pconsps1_2_archvg_dt_2', '', ['tconsps20', 'tconsps21'], ''),
              ('pconsps1_2_caavg_dt', '', ['tconsps20', 'tconsps21'], ''),
              ('pconsps1_2_ora1vg_dt_1', '', ['tconsps20', 'tconsps21'], ''),
              ('pconsps1_2_ora1vg_dt_2', '', ['tconsps20', 'tconsps21'], ''),
              ('pconsps1_2_ora1vg_dt_3', '', ['tconsps20', 'tconsps21'], ''),
              ('pconsps1_2_ora1vg_dt_4', '', ['tconsps20', 'tconsps21'], ''),
              ('pconsps1_2_ora1vg_dt_5', '', ['tconsps20', 'tconsps21'], ''),
              ('pconsps1_2_ora1vg_dt_6', '', ['tconsps20', 'tconsps21'], ''),
              ('pconsps1_2_ora1vg_dt_7', '', ['tconsps20', 'tconsps21'], ''),
              ('pconsps1_2_sps1redovg_dt_1', '', ['tconsps20', 'tconsps21'], ''),
              ('pconsps1_2_sps1redovg_dt_2', '', ['tconsps20', 'tconsps21'], ''),
              ('pconsps1_root_sysvg_dt_1', '', ['tconsps20'], ''),
              ('pconsps1_root_sysvg_dt_2', '', ['tconsps20'], ''),
              ('pconsps1_root_sysvg_dt_3', '', ['tconsps20'], ''),
              ('pconsps2_root_sysvg_dt1', '', ['tconsps21'], ''),
              ('pconsps2_root_sysvg_dt2', '', ['tconsps21'], ''),
              ('pconsps2_root_sysvg_dt3', '', ['tconsps21'], ''),
              ('TLA-WANMFS01_02_500GB1', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_500GB2', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_500GB3', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_500GB4', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_500GB5', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_250GB_1', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_250GB_2', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_250GB_3', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_250GB_4', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_250GB_5', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_250GB_6', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_250GB_7', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_250GB_8', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_250GB_9', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_250GB_10', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_5GB1', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_5GB2', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_5GB3', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_5GB4', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_5GB5', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_5GB6', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_5GB7', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_5GB8', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_5GB9', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_5GB10', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_5GB11', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_5GB12', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_5GB13', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_5GB14', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_5GB15', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_5GB16', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_5GB17', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_5GB18', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_5GB19', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_5GB20', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_50GB_1', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_50GB_2', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_50GB_3', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], ''),
              ('TLA-WANMFS01_02_50GB_4', '', ['TLA_WANMFS01', 'TLA_WANMFS02'], '')]},
 {'id': 'template-tempe-az',
  'location': 'Tempe, AZ',
  'profile': 'ibm_storwize_v7000_g3',
  'pool': 'G2_TMP_Pool',
  'hosts': ['bib-tempedc.vm01.walgreens.com',
            'bib-tempedc.vm02.walgreens.com',
            'dtmptst1',
            'ptmpnw1',
            'ptmporldb1',
            'ptmppls1',
            'ptmppls2',
            'ptmpres01',
            'ptmpvio01a',
            'ptmpvio01b',
            'ptmpvio02a',
            'ptmpvio02b'],
  'volumes': [('ptmpnw1_VM', '2.49 TiB', [], ''),
              ('ptmpvm1_2_0', '2.00 TiB', [], ''),
              ('ptmpvm1_2_1', '4.00 TiB', [], ''),
              ('dtmptst2_root_1', '', [], ''),
              ('dtmptst2_root_2', '', [], ''),
              ('dtmptst2_root_3', '', [], ''),
              ('dtmptst2_ora_1', '', [], ''),
              ('dtmptst2_ora_2', '', [], ''),
              ('dtmptst2_ora_3', '', [], ''),
              ('dtmptst2_ora_4', '', [], ''),
              ('ptmpnw1_1', '', [], ''),
              ('ptmpnw1_2', '', [], ''),
              ('ptmpnw1_3', '', [], ''),
              ('ptmporldb1_root_1', '', [], ''),
              ('ptmporldb1_root_2', '', [], ''),
              ('ptmporldb1_root_3', '', [], ''),
              ('ptmporldb1_ora_1', '', [], ''),
              ('ptmporldb1_ora_2', '', [], ''),
              ('ptmporldb1_ora_3', '', [], ''),
              ('ptmporldb1_ora_4', '', [], ''),
              ('ptmporldb1_ora_5', '', [], ''),
              ('ptmporldb1_ora_6', '', [], ''),
              ('ptmporldb1_ora_7', '', [], ''),
              ('ptmporldb1_ora_8', '', [], ''),
              ('ptmporldb1_ora_9', '', [], ''),
              ('ptmporldb1_ora_10', '', [], ''),
              ('ptmporldb_ora_11', '', [], ''),
              ('ptmporldb_ora_12', '', [], ''),
              ('ptmporldb_ora_13', '', [], ''),
              ('ptmppls1_root_1', '', [], ''),
              ('ptmppls1_root_2', '', [], ''),
              ('ptmppls1_root_3', '', [], ''),
              ('ptmppls2_root_1', '', [], ''),
              ('ptmppls2_root_2', '', [], ''),
              ('ptmppls2_root_3', '', [], ''),
              ('ptmppls_db_1', '', [], ''),
              ('ptmppls_db_2', '', [], ''),
              ('ptmppls_db_3', '', [], ''),
              ('ptmppls_db_4', '', [], ''),
              ('ptmppls_db_5', '', [], ''),
              ('ptmppls_db_6', '', [], ''),
              ('ptmppls_db_7', '', [], ''),
              ('ptmppls_db_8', '', [], ''),
              ('ptmppls_db_9', '', [], ''),
              ('ptmppls_db_10', '', [], ''),
              ('ptmppls_db_11', '', [], ''),
              ('ptmppls_db_12', '', [], ''),
              ('ptmppls_db_13', '', [], ''),
              ('ptmppls_HA', '', [], ''),
              ('ptmppls_db_14', '', [], ''),
              ('ptmppls_db_15', '', [], ''),
              ('ptmppls_db_16', '', [], ''),
              ('ptmppls_db_17', '', [], ''),
              ('ptmppls_db_18', '', [], ''),
              ('ptmppls_db_19', '', [], ''),
              ('ptmppls_db_20', '', [], ''),
              ('ptmppls_db_21', '', [], ''),
              ('ptmppls_db_22', '', [], ''),
              ('ptmppls_db_23', '', [], ''),
              ('ptmpres01_00', '', [], ''),
              ('ptmpres01_01', '', [], ''),
              ('ptmpres01_02', '', [], ''),
              ('ptmpres01_03', '', [], ''),
              ('ptmpres01_04', '', [], ''),
              ('ptmpvio01a_0', '', [], ''),
              ('ptmpvio01a_1', '', [], ''),
              ('ptmpvio01b_0', '', [], ''),
              ('ptmpvio01b_1', '', [], ''),
              ('ptmpvio02a_0', '', [], ''),
              ('ptmpvio02a_1', '', [], ''),
              ('ptmpvio02b_0', '', [], ''),
              ('ptmpvio02b_1', '', [], '')]}]

def _generic_host(name: str) -> dict:
    return {
        "lpar_name": name,
        "slot": "",
        "state": "",
        "required": False,
        "type": "Generic",
        "remote_lpar": "",
        "remote_slot": "",
        "wwpn1": "",
        "wwpn2": "",
        "physical_fc_slot": "",
        "managed_system_name": "",
        "managed_system_serial": "",
        "notes": "",
    }


def _exact_lun(
    volume_name: str,
    size: str,
    host_names: list[str],
    scsi_or_lun_id: str,
    *,
    profile: str,
    pool: str,
    hint: str,
) -> dict:
    return {
        "purpose": volume_name,
        "count": 1,
        "size": size,
        "shared": len(host_names) >= 2,
        "storage_profile": profile,
        "pool_or_cpg": pool,
        "host_names": host_names,
        "scsi_or_lun_id": scsi_or_lun_id,
        "card_hint": hint,
        "cluster": "",
        "name_prefix": "",
        "exact_name": True,
    }


def build_six_site_templates() -> list[dict]:
    templates: list[dict] = []
    for inventory in _SITE_INVENTORIES:
        location = inventory["location"]
        profile = inventory["profile"]
        pool = inventory["pool"]
        templates.append(
            {
                "id": inventory["id"],
                "name": f"{location} (Template)",
                "location": location,
                "notes": (
                    "Seeded from the site lookup HTML inventory. WWPNs are blank; "
                    "Sync Inventory can refresh hosts and mapped volumes."
                ),
                "is_template": True,
                "default_storage_profile": profile,
                "default_pool_or_cpg": pool,
                "default_card_hint": location,
                "hosts": [_generic_host(name) for name in inventory["hosts"]],
                "luns": [
                    _exact_lun(
                        name,
                        size,
                        hosts,
                        scsi,
                        profile=profile,
                        pool=pool,
                        hint=location,
                    )
                    for name, size, hosts, scsi in inventory["volumes"]
                ],
            }
        )
    return templates
